CREATE TABLE IF NOT EXISTS advisor_alert_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  client_uid bigint,
  kind text,
  message text,
  pct double precision,
  fired_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  delivered_push bigint NOT NULL DEFAULT 0,
  delivered_email bigint NOT NULL DEFAULT 0,
  seen bigint NOT NULL DEFAULT 0
);

ALTER TABLE advisor_alert_events ADD COLUMN IF NOT EXISTS advisor_uid bigint;

ALTER TABLE advisor_alert_events ADD COLUMN IF NOT EXISTS client_uid bigint;

ALTER TABLE advisor_alert_events ADD COLUMN IF NOT EXISTS kind text;

ALTER TABLE advisor_alert_events ADD COLUMN IF NOT EXISTS message text;

ALTER TABLE advisor_alert_events ADD COLUMN IF NOT EXISTS pct double precision;

ALTER TABLE advisor_alert_events ADD COLUMN IF NOT EXISTS fired_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE advisor_alert_events ADD COLUMN IF NOT EXISTS delivered_push bigint DEFAULT 0;

ALTER TABLE advisor_alert_events ADD COLUMN IF NOT EXISTS delivered_email bigint DEFAULT 0;

ALTER TABLE advisor_alert_events ADD COLUMN IF NOT EXISTS seen bigint DEFAULT 0;

CREATE TABLE IF NOT EXISTS advisor_alert_state (
  advisor_uid bigint NOT NULL,
  client_uid bigint NOT NULL,
  armed bigint NOT NULL DEFAULT 1,
  last_fired_date text,
  PRIMARY KEY (advisor_uid, client_uid)
);

ALTER TABLE advisor_alert_state ADD COLUMN IF NOT EXISTS advisor_uid bigint;

ALTER TABLE advisor_alert_state ADD COLUMN IF NOT EXISTS client_uid bigint;

ALTER TABLE advisor_alert_state ADD COLUMN IF NOT EXISTS armed bigint DEFAULT 1;

ALTER TABLE advisor_alert_state ADD COLUMN IF NOT EXISTS last_fired_date text;

CREATE TABLE IF NOT EXISTS advisor_alerts (
  advisor_uid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  up_pct double precision,
  down_pct double precision,
  channel text NOT NULL DEFAULT 'both',
  active bigint NOT NULL DEFAULT 1,
  group_id bigint,
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE advisor_alerts ADD COLUMN IF NOT EXISTS up_pct double precision;

ALTER TABLE advisor_alerts ADD COLUMN IF NOT EXISTS down_pct double precision;

ALTER TABLE advisor_alerts ADD COLUMN IF NOT EXISTS channel text DEFAULT 'both';

ALTER TABLE advisor_alerts ADD COLUMN IF NOT EXISTS active bigint DEFAULT 1;

ALTER TABLE advisor_alerts ADD COLUMN IF NOT EXISTS group_id bigint;

ALTER TABLE advisor_alerts ADD COLUMN IF NOT EXISTS updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS advisor_brief_log (
  advisor_uid bigint NOT NULL,
  kind text NOT NULL,
  date text NOT NULL,
  sent_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (advisor_uid, kind, date)
);

ALTER TABLE advisor_brief_log ADD COLUMN IF NOT EXISTS advisor_uid bigint;

ALTER TABLE advisor_brief_log ADD COLUMN IF NOT EXISTS kind text;

ALTER TABLE advisor_brief_log ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE advisor_brief_log ADD COLUMN IF NOT EXISTS sent_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS advisor_claim_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  advisor_uid bigint NOT NULL,
  token text NOT NULL,
  email text NOT NULL,
  expires_at text NOT NULL,
  used_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (token)
);

ALTER TABLE advisor_claim_tokens ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE advisor_claim_tokens ADD COLUMN IF NOT EXISTS advisor_uid bigint;

ALTER TABLE advisor_claim_tokens ADD COLUMN IF NOT EXISTS token text;

ALTER TABLE advisor_claim_tokens ADD COLUMN IF NOT EXISTS email text;

ALTER TABLE advisor_claim_tokens ADD COLUMN IF NOT EXISTS expires_at text;

ALTER TABLE advisor_claim_tokens ADD COLUMN IF NOT EXISTS used_at text;

ALTER TABLE advisor_claim_tokens ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS advisor_clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  client_uid bigint NOT NULL,
  link_type text NOT NULL DEFAULT 'managed',
  permission text NOT NULL DEFAULT 'read_write',
  status text NOT NULL DEFAULT 'active',
  label text,
  notes text,
  consent_ref text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  revoked_at text,
  phone text,
  UNIQUE (advisor_uid, client_uid)
);

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS advisor_uid bigint;

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS client_uid bigint;

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS link_type text DEFAULT 'managed';

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS permission text DEFAULT 'read_write';

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS label text;

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS consent_ref text;

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS revoked_at text;

ALTER TABLE advisor_clients ADD COLUMN IF NOT EXISTS phone text;

CREATE TABLE IF NOT EXISTS advisor_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  name text NOT NULL,
  rules text NOT NULL DEFAULT '{}',
  excluded text NOT NULL DEFAULT '[]',
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE advisor_groups ADD COLUMN IF NOT EXISTS advisor_uid bigint;

ALTER TABLE advisor_groups ADD COLUMN IF NOT EXISTS name text;

ALTER TABLE advisor_groups ADD COLUMN IF NOT EXISTS rules text DEFAULT '{}';

ALTER TABLE advisor_groups ADD COLUMN IF NOT EXISTS excluded text DEFAULT '[]';

ALTER TABLE advisor_groups ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS advisor_op_batch_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id bigint NOT NULL,
  client_uid bigint NOT NULL,
  position_id bigint,
  status text NOT NULL DEFAULT 'ok',
  cost_debited double precision,
  autodep_native double precision,
  autodep_usd double precision,
  autodep_ym text
);

ALTER TABLE advisor_op_batch_items ADD COLUMN IF NOT EXISTS batch_id bigint;

ALTER TABLE advisor_op_batch_items ADD COLUMN IF NOT EXISTS client_uid bigint;

ALTER TABLE advisor_op_batch_items ADD COLUMN IF NOT EXISTS position_id bigint;

ALTER TABLE advisor_op_batch_items ADD COLUMN IF NOT EXISTS status text DEFAULT 'ok';

ALTER TABLE advisor_op_batch_items ADD COLUMN IF NOT EXISTS cost_debited double precision;

ALTER TABLE advisor_op_batch_items ADD COLUMN IF NOT EXISTS autodep_native double precision;

ALTER TABLE advisor_op_batch_items ADD COLUMN IF NOT EXISTS autodep_usd double precision;

ALTER TABLE advisor_op_batch_items ADD COLUMN IF NOT EXISTS autodep_ym text;

CREATE TABLE IF NOT EXISTS advisor_op_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  asset text NOT NULL,
  op_kind text NOT NULL DEFAULT 'buy',
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  undone_at text
);

ALTER TABLE advisor_op_batches ADD COLUMN IF NOT EXISTS advisor_uid bigint;

ALTER TABLE advisor_op_batches ADD COLUMN IF NOT EXISTS asset text;

ALTER TABLE advisor_op_batches ADD COLUMN IF NOT EXISTS op_kind text DEFAULT 'buy';

ALTER TABLE advisor_op_batches ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE advisor_op_batches ADD COLUMN IF NOT EXISTS undone_at text;

CREATE TABLE IF NOT EXISTS advisor_profile (
  advisor_uid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name text,
  cnv_matricula text,
  logo_data text,
  brief_open bigint DEFAULT 1,
  brief_close bigint DEFAULT 1,
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE advisor_profile ADD COLUMN IF NOT EXISTS display_name text;

ALTER TABLE advisor_profile ADD COLUMN IF NOT EXISTS cnv_matricula text;

ALTER TABLE advisor_profile ADD COLUMN IF NOT EXISTS logo_data text;

ALTER TABLE advisor_profile ADD COLUMN IF NOT EXISTS brief_open bigint DEFAULT 1;

ALTER TABLE advisor_profile ADD COLUMN IF NOT EXISTS brief_close bigint DEFAULT 1;

ALTER TABLE advisor_profile ADD COLUMN IF NOT EXISTS updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS advisor_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  client_uid bigint NOT NULL,
  period_start text NOT NULL,
  period_end text NOT NULL,
  token text NOT NULL,
  payload text NOT NULL,
  wa_text text,
  revoked_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (token)
);

ALTER TABLE advisor_reports ADD COLUMN IF NOT EXISTS advisor_uid bigint;

ALTER TABLE advisor_reports ADD COLUMN IF NOT EXISTS client_uid bigint;

ALTER TABLE advisor_reports ADD COLUMN IF NOT EXISTS period_start text;

ALTER TABLE advisor_reports ADD COLUMN IF NOT EXISTS period_end text;

ALTER TABLE advisor_reports ADD COLUMN IF NOT EXISTS token text;

ALTER TABLE advisor_reports ADD COLUMN IF NOT EXISTS payload text;

ALTER TABLE advisor_reports ADD COLUMN IF NOT EXISTS wa_text text;

ALTER TABLE advisor_reports ADD COLUMN IF NOT EXISTS revoked_at text;

ALTER TABLE advisor_reports ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS ai_analyses_cache (
  cache_key text,
  user_id bigint NOT NULL,
  screen text NOT NULL,
  result_json text NOT NULL,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  expires_at text NOT NULL,
  packet_hash text NOT NULL,
  model text,
  input_tokens bigint DEFAULT 0,
  output_tokens bigint DEFAULT 0,
  cache_read_tokens bigint DEFAULT 0,
  cache_create_tokens bigint DEFAULT 0,
  cost_usd_cents bigint DEFAULT 0,
  PRIMARY KEY (cache_key)
);

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS cache_key text;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS screen text;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS result_json text;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS expires_at text;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS packet_hash text;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS model text;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS input_tokens bigint DEFAULT 0;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS output_tokens bigint DEFAULT 0;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS cache_read_tokens bigint DEFAULT 0;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS cache_create_tokens bigint DEFAULT 0;

ALTER TABLE ai_analyses_cache ADD COLUMN IF NOT EXISTS cost_usd_cents bigint DEFAULT 0;

CREATE TABLE IF NOT EXISTS ai_tool_usage (
  user_id bigint NOT NULL,
  date text NOT NULL,
  tool_name text NOT NULL,
  count bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, date, tool_name)
);

ALTER TABLE ai_tool_usage ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE ai_tool_usage ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE ai_tool_usage ADD COLUMN IF NOT EXISTS tool_name text;

ALTER TABLE ai_tool_usage ADD COLUMN IF NOT EXISTS count bigint DEFAULT 0;

CREATE TABLE IF NOT EXISTS ai_usage_daily (
  user_id bigint NOT NULL,
  date text NOT NULL,
  analyses_count bigint NOT NULL DEFAULT 0,
  hub_queries_count bigint NOT NULL DEFAULT 0,
  chat_count bigint NOT NULL DEFAULT 0,
  diag_dismiss_count bigint NOT NULL DEFAULT 0,
  cost_usd_cents bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, date)
);

ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS analyses_count bigint DEFAULT 0;

ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS hub_queries_count bigint DEFAULT 0;

ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS chat_count bigint DEFAULT 0;

ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS diag_dismiss_count bigint DEFAULT 0;

ALTER TABLE ai_usage_daily ADD COLUMN IF NOT EXISTS cost_usd_cents bigint DEFAULT 0;

CREATE TABLE IF NOT EXISTS ai_user_facts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  content text NOT NULL,
  source text NOT NULL DEFAULT 'user_correction',
  is_active bigint NOT NULL DEFAULT 1,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE ai_user_facts ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE ai_user_facts ADD COLUMN IF NOT EXISTS content text;

ALTER TABLE ai_user_facts ADD COLUMN IF NOT EXISTS source text DEFAULT 'user_correction';

ALTER TABLE ai_user_facts ADD COLUMN IF NOT EXISTS is_active bigint DEFAULT 1;

ALTER TABLE ai_user_facts ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE ai_user_facts ADD COLUMN IF NOT EXISTS updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS alert_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id bigint NOT NULL,
  user_id bigint NOT NULL,
  symbol text,
  fired_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  price double precision,
  message text,
  delivered_push bigint NOT NULL DEFAULT 0,
  delivered_email bigint NOT NULL DEFAULT 0,
  seen bigint NOT NULL DEFAULT 0
);

ALTER TABLE alert_events ADD COLUMN IF NOT EXISTS alert_id bigint;

ALTER TABLE alert_events ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE alert_events ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE alert_events ADD COLUMN IF NOT EXISTS fired_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE alert_events ADD COLUMN IF NOT EXISTS price double precision;

ALTER TABLE alert_events ADD COLUMN IF NOT EXISTS message text;

ALTER TABLE alert_events ADD COLUMN IF NOT EXISTS delivered_push bigint DEFAULT 0;

ALTER TABLE alert_events ADD COLUMN IF NOT EXISTS delivered_email bigint DEFAULT 0;

ALTER TABLE alert_events ADD COLUMN IF NOT EXISTS seen bigint DEFAULT 0;

CREATE TABLE IF NOT EXISTS alert_symbol_state (
  alert_id bigint NOT NULL,
  symbol text NOT NULL,
  armed bigint NOT NULL DEFAULT 1,
  last_fired_date text,
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (alert_id, symbol)
);

ALTER TABLE alert_symbol_state ADD COLUMN IF NOT EXISTS alert_id bigint;

ALTER TABLE alert_symbol_state ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE alert_symbol_state ADD COLUMN IF NOT EXISTS armed bigint DEFAULT 1;

ALTER TABLE alert_symbol_state ADD COLUMN IF NOT EXISTS last_fired_date text;

ALTER TABLE alert_symbol_state ADD COLUMN IF NOT EXISTS updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS alerts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  kind text NOT NULL,
  symbol text,
  scope text NOT NULL DEFAULT 'ticker',
  direction text NOT NULL DEFAULT 'either',
  threshold double precision,
  up_pct double precision,
  down_pct double precision,
  currency text,
  baseline text DEFAULT 'prev_close',
  anchor_price double precision,
  channel text NOT NULL DEFAULT 'both',
  repeat text NOT NULL DEFAULT 'once',
  cooldown_min bigint NOT NULL DEFAULT 360,
  armed bigint NOT NULL DEFAULT 1,
  active bigint NOT NULL DEFAULT 1,
  note text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_evaluated_at text,
  last_fired_at text,
  last_fired_price double precision
);

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS kind text;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS scope text DEFAULT 'ticker';

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS direction text DEFAULT 'either';

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS threshold double precision;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS up_pct double precision;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS down_pct double precision;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS currency text;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS baseline text DEFAULT 'prev_close';

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS anchor_price double precision;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS channel text DEFAULT 'both';

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS repeat text DEFAULT 'once';

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS cooldown_min bigint DEFAULT 360;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS armed bigint DEFAULT 1;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS active bigint DEFAULT 1;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS note text;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS last_evaluated_at text;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS last_fired_at text;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS last_fired_price double precision;

CREATE TABLE IF NOT EXISTS archived_positions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  section text NOT NULL,
  label text,
  payload text NOT NULL,
  count bigint NOT NULL DEFAULT 0,
  archived_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE archived_positions ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE archived_positions ADD COLUMN IF NOT EXISTS section text;

ALTER TABLE archived_positions ADD COLUMN IF NOT EXISTS label text;

ALTER TABLE archived_positions ADD COLUMN IF NOT EXISTS payload text;

ALTER TABLE archived_positions ADD COLUMN IF NOT EXISTS count bigint DEFAULT 0;

ALTER TABLE archived_positions ADD COLUMN IF NOT EXISTS archived_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS asset_last_price (
  symbol text,
  price double precision NOT NULL,
  updated_at text NOT NULL,
  PRIMARY KEY (symbol)
);

ALTER TABLE asset_last_price ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE asset_last_price ADD COLUMN IF NOT EXISTS price double precision;

ALTER TABLE asset_last_price ADD COLUMN IF NOT EXISTS updated_at text;

CREATE TABLE IF NOT EXISTS asset_price_history (
  symbol text NOT NULL,
  date text NOT NULL,
  price double precision NOT NULL,
  source text,
  fetched_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (symbol, date)
);

ALTER TABLE asset_price_history ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE asset_price_history ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE asset_price_history ADD COLUMN IF NOT EXISTS price double precision;

ALTER TABLE asset_price_history ADD COLUMN IF NOT EXISTS source text;

ALTER TABLE asset_price_history ADD COLUMN IF NOT EXISTS fetched_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS billing_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mp_event_id text,
  mp_event_type text,
  mp_data_id text,
  user_id bigint,
  signature_valid bigint DEFAULT 0,
  processed bigint DEFAULT 0,
  raw_payload text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE billing_events ADD COLUMN IF NOT EXISTS mp_event_id text;

ALTER TABLE billing_events ADD COLUMN IF NOT EXISTS mp_event_type text;

ALTER TABLE billing_events ADD COLUMN IF NOT EXISTS mp_data_id text;

ALTER TABLE billing_events ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE billing_events ADD COLUMN IF NOT EXISTS signature_valid bigint DEFAULT 0;

ALTER TABLE billing_events ADD COLUMN IF NOT EXISTS processed bigint DEFAULT 0;

ALTER TABLE billing_events ADD COLUMN IF NOT EXISTS raw_payload text;

ALTER TABLE billing_events ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS bond_cashflow_skips (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  broker text NOT NULL,
  asset text NOT NULL,
  date text NOT NULL,
  reason text,
  created_at text NOT NULL,
  UNIQUE (user_id, broker, asset, date)
);

ALTER TABLE bond_cashflow_skips ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE bond_cashflow_skips ADD COLUMN IF NOT EXISTS broker text;

ALTER TABLE bond_cashflow_skips ADD COLUMN IF NOT EXISTS asset text;

ALTER TABLE bond_cashflow_skips ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE bond_cashflow_skips ADD COLUMN IF NOT EXISTS reason text;

ALTER TABLE bond_cashflow_skips ADD COLUMN IF NOT EXISTS created_at text;

CREATE TABLE IF NOT EXISTS bond_indices_daily (
  index_name text NOT NULL,
  date text NOT NULL,
  value double precision NOT NULL,
  source text,
  updated_at text NOT NULL,
  PRIMARY KEY (index_name, date)
);

ALTER TABLE bond_indices_daily ADD COLUMN IF NOT EXISTS index_name text;

ALTER TABLE bond_indices_daily ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE bond_indices_daily ADD COLUMN IF NOT EXISTS value double precision;

ALTER TABLE bond_indices_daily ADD COLUMN IF NOT EXISTS source text;

ALTER TABLE bond_indices_daily ADD COLUMN IF NOT EXISTS updated_at text;

CREATE TABLE IF NOT EXISTS broadcast_send_log (
  content_hash text NOT NULL,
  email text NOT NULL,
  sent_at text NOT NULL DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (content_hash, email)
);

ALTER TABLE broadcast_send_log ADD COLUMN IF NOT EXISTS content_hash text;

ALTER TABLE broadcast_send_log ADD COLUMN IF NOT EXISTS email text;

ALTER TABLE broadcast_send_log ADD COLUMN IF NOT EXISTS sent_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS brokers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name text NOT NULL,
  currency text NOT NULL DEFAULT 'USDT',
  parent_broker_id bigint,
  UNIQUE (user_id, name)
);

ALTER TABLE brokers ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE brokers ADD COLUMN IF NOT EXISTS name text;

ALTER TABLE brokers ADD COLUMN IF NOT EXISTS currency text DEFAULT 'USDT';

ALTER TABLE brokers ADD COLUMN IF NOT EXISTS parent_broker_id bigint;

CREATE TABLE IF NOT EXISTS config (
  key text NOT NULL,
  value text,
  user_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (key, user_id)
);

ALTER TABLE config ADD COLUMN IF NOT EXISTS key text;

ALTER TABLE config ADD COLUMN IF NOT EXISTS value text;

ALTER TABLE config ADD COLUMN IF NOT EXISTS user_id bigint DEFAULT 0;

CREATE TABLE IF NOT EXISTS credit_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  kind text NOT NULL,
  amount_usd double precision NOT NULL,
  days_delta double precision NOT NULL,
  from_plan text,
  from_period text,
  to_plan text,
  to_period text,
  active_until_before text,
  active_until_after text,
  source_subscription_id text,
  payment_id text,
  note text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS kind text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS amount_usd double precision;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS days_delta double precision;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS from_plan text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS from_period text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS to_plan text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS to_period text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS active_until_before text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS active_until_after text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS source_subscription_id text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS payment_id text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS note text;

ALTER TABLE credit_ledger ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS deleted_ops_journal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  token text NOT NULL,
  kind text NOT NULL,
  payload_json text NOT NULL,
  since_date text,
  broker text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  undone_at text
);

ALTER TABLE deleted_ops_journal ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE deleted_ops_journal ADD COLUMN IF NOT EXISTS token text;

ALTER TABLE deleted_ops_journal ADD COLUMN IF NOT EXISTS kind text;

ALTER TABLE deleted_ops_journal ADD COLUMN IF NOT EXISTS payload_json text;

ALTER TABLE deleted_ops_journal ADD COLUMN IF NOT EXISTS since_date text;

ALTER TABLE deleted_ops_journal ADD COLUMN IF NOT EXISTS broker text;

ALTER TABLE deleted_ops_journal ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE deleted_ops_journal ADD COLUMN IF NOT EXISTS undone_at text;

CREATE TABLE IF NOT EXISTS email_verification_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  code text NOT NULL,
  expires_at text NOT NULL,
  used_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE email_verification_codes ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE email_verification_codes ADD COLUMN IF NOT EXISTS code text;

ALTER TABLE email_verification_codes ADD COLUMN IF NOT EXISTS expires_at text;

ALTER TABLE email_verification_codes ADD COLUMN IF NOT EXISTS used_at text;

ALTER TABLE email_verification_codes ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS fci_catalog (
  symbol text,
  ad_name text NOT NULL,
  display_name text NOT NULL,
  emisor text,
  clase text,
  moneda text NOT NULL DEFAULT 'ARS',
  categoria text,
  activo bigint NOT NULL DEFAULT 1,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (symbol)
);

ALTER TABLE fci_catalog ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE fci_catalog ADD COLUMN IF NOT EXISTS ad_name text;

ALTER TABLE fci_catalog ADD COLUMN IF NOT EXISTS display_name text;

ALTER TABLE fci_catalog ADD COLUMN IF NOT EXISTS emisor text;

ALTER TABLE fci_catalog ADD COLUMN IF NOT EXISTS clase text;

ALTER TABLE fci_catalog ADD COLUMN IF NOT EXISTS moneda text DEFAULT 'ARS';

ALTER TABLE fci_catalog ADD COLUMN IF NOT EXISTS categoria text;

ALTER TABLE fci_catalog ADD COLUMN IF NOT EXISTS activo bigint DEFAULT 1;

ALTER TABLE fci_catalog ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS fci_prices (
  symbol text,
  price double precision,
  moneda text,
  as_of_date text,
  fetched_at text,
  PRIMARY KEY (symbol)
);

ALTER TABLE fci_prices ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE fci_prices ADD COLUMN IF NOT EXISTS price double precision;

ALTER TABLE fci_prices ADD COLUMN IF NOT EXISTS moneda text;

ALTER TABLE fci_prices ADD COLUMN IF NOT EXISTS as_of_date text;

ALTER TABLE fci_prices ADD COLUMN IF NOT EXISTS fetched_at text;

CREATE TABLE IF NOT EXISTS financial_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker text NOT NULL,
  event_type text NOT NULL,
  event_date text NOT NULL,
  details text,
  confirmed bigint DEFAULT 0,
  source text,
  fetched_at text NOT NULL,
  UNIQUE (ticker, event_type, event_date)
);

ALTER TABLE financial_events ADD COLUMN IF NOT EXISTS ticker text;

ALTER TABLE financial_events ADD COLUMN IF NOT EXISTS event_type text;

ALTER TABLE financial_events ADD COLUMN IF NOT EXISTS event_date text;

ALTER TABLE financial_events ADD COLUMN IF NOT EXISTS details text;

ALTER TABLE financial_events ADD COLUMN IF NOT EXISTS confirmed bigint DEFAULT 0;

ALTER TABLE financial_events ADD COLUMN IF NOT EXISTS source text;

ALTER TABLE financial_events ADD COLUMN IF NOT EXISTS fetched_at text;

CREATE TABLE IF NOT EXISTS futures_positions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  broker text NOT NULL,
  symbol text NOT NULL,
  base_asset text,
  side text NOT NULL DEFAULT 'long',
  quantity double precision NOT NULL,
  entry_price double precision NOT NULL,
  leverage double precision,
  margin_usd double precision,
  liquidation_price double precision,
  opened_at text NOT NULL,
  notes text,
  closed_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS broker text;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS base_asset text;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS side text DEFAULT 'long';

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS quantity double precision;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS entry_price double precision;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS leverage double precision;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS margin_usd double precision;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS liquidation_price double precision;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS opened_at text;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS closed_at text;

ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS fx_rates_daily (
  date text,
  blue_venta double precision NOT NULL,
  mep_venta double precision,
  source text DEFAULT 'unknown',
  fetched_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (date)
);

ALTER TABLE fx_rates_daily ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE fx_rates_daily ADD COLUMN IF NOT EXISTS blue_venta double precision;

ALTER TABLE fx_rates_daily ADD COLUMN IF NOT EXISTS mep_venta double precision;

ALTER TABLE fx_rates_daily ADD COLUMN IF NOT EXISTS source text DEFAULT 'unknown';

ALTER TABLE fx_rates_daily ADD COLUMN IF NOT EXISTS fetched_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  target_usd double precision NOT NULL,
  target_date text NOT NULL,
  expected_return_pct double precision NOT NULL DEFAULT 10,
  label text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE goals ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE goals ADD COLUMN IF NOT EXISTS target_usd double precision;

ALTER TABLE goals ADD COLUMN IF NOT EXISTS target_date text;

ALTER TABLE goals ADD COLUMN IF NOT EXISTS expected_return_pct double precision DEFAULT 10;

ALTER TABLE goals ADD COLUMN IF NOT EXISTS label text;

ALTER TABLE goals ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS import_batches (
  id text,
  user_id bigint NOT NULL,
  broker text NOT NULL,
  parser_format text NOT NULL,
  file_name text,
  file_hash text NOT NULL,
  total_rows bigint NOT NULL DEFAULT 0,
  valid_rows bigint NOT NULL DEFAULT 0,
  invalid_rows bigint NOT NULL DEFAULT 0,
  status text NOT NULL,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  confirmed_at text,
  reverted_at text,
  route_by_currency bigint NOT NULL DEFAULT 0,
  fund_price_overrides text,
  override_info text,
  PRIMARY KEY (id)
);

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS id text;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS broker text;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS parser_format text;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS file_name text;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS file_hash text;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS total_rows bigint DEFAULT 0;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS valid_rows bigint DEFAULT 0;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS invalid_rows bigint DEFAULT 0;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS status text;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS confirmed_at text;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS reverted_at text;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS route_by_currency bigint DEFAULT 0;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS fund_price_overrides text;

ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS override_info text;

CREATE TABLE IF NOT EXISTS import_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name text NOT NULL,
  mapping_json text NOT NULL,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (user_id, name)
);

ALTER TABLE import_mappings ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE import_mappings ADD COLUMN IF NOT EXISTS name text;

ALTER TABLE import_mappings ADD COLUMN IF NOT EXISTS mapping_json text;

ALTER TABLE import_mappings ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS import_normalized_tx (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id text NOT NULL,
  raw_row_id bigint NOT NULL,
  date text NOT NULL,
  broker text NOT NULL DEFAULT '',
  operation_type text NOT NULL,
  asset_symbol text,
  asset_name text,
  asset_type text,
  quantity double precision,
  unit_price double precision,
  gross_amount double precision,
  fees double precision DEFAULT 0,
  taxes double precision DEFAULT 0,
  currency text,
  settlement_currency text,
  notes text,
  created_position_id bigint,
  created_operation_id bigint,
  transfer_out bigint NOT NULL DEFAULT 0,
  tc_compra double precision,
  excluded_at text,
  excluded_by bigint,
  fingerprint text,
  gross_amount_usd double precision
);

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS batch_id text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS raw_row_id bigint;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS broker text DEFAULT '';

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS operation_type text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS asset_symbol text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS asset_name text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS asset_type text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS quantity double precision;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS unit_price double precision;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS gross_amount double precision;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS fees double precision DEFAULT 0;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS taxes double precision DEFAULT 0;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS currency text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS settlement_currency text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS created_position_id bigint;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS created_operation_id bigint;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS transfer_out bigint DEFAULT 0;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS tc_compra double precision;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS excluded_at text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS excluded_by bigint;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS fingerprint text;

ALTER TABLE import_normalized_tx ADD COLUMN IF NOT EXISTS gross_amount_usd double precision;

CREATE TABLE IF NOT EXISTS import_op_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id text NOT NULL,
  raw_row_id bigint,
  position_id bigint,
  operation_id bigint
);

ALTER TABLE import_op_links ADD COLUMN IF NOT EXISTS batch_id text;

ALTER TABLE import_op_links ADD COLUMN IF NOT EXISTS raw_row_id bigint;

ALTER TABLE import_op_links ADD COLUMN IF NOT EXISTS position_id bigint;

ALTER TABLE import_op_links ADD COLUMN IF NOT EXISTS operation_id bigint;

CREATE TABLE IF NOT EXISTS import_raw_rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id text NOT NULL,
  row_index bigint NOT NULL,
  raw_json text NOT NULL,
  status text NOT NULL,
  errors_json text
);

ALTER TABLE import_raw_rows ADD COLUMN IF NOT EXISTS batch_id text;

ALTER TABLE import_raw_rows ADD COLUMN IF NOT EXISTS row_index bigint;

ALTER TABLE import_raw_rows ADD COLUMN IF NOT EXISTS raw_json text;

ALTER TABLE import_raw_rows ADD COLUMN IF NOT EXISTS status text;

ALTER TABLE import_raw_rows ADD COLUMN IF NOT EXISTS errors_json text;

CREATE TABLE IF NOT EXISTS iol_lab_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  started_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  finished_at text,
  status text NOT NULL DEFAULT 'running',
  summary text,
  result_json text,
  error text
);

ALTER TABLE iol_lab_runs ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE iol_lab_runs ADD COLUMN IF NOT EXISTS started_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE iol_lab_runs ADD COLUMN IF NOT EXISTS finished_at text;

ALTER TABLE iol_lab_runs ADD COLUMN IF NOT EXISTS status text DEFAULT 'running';

ALTER TABLE iol_lab_runs ADD COLUMN IF NOT EXISTS summary text;

ALTER TABLE iol_lab_runs ADD COLUMN IF NOT EXISTS result_json text;

ALTER TABLE iol_lab_runs ADD COLUMN IF NOT EXISTS error text;

CREATE TABLE IF NOT EXISTS iol_lab_token_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  ok bigint NOT NULL,
  detail text
);

ALTER TABLE iol_lab_token_log ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE iol_lab_token_log ADD COLUMN IF NOT EXISTS at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE iol_lab_token_log ADD COLUMN IF NOT EXISTS ok bigint;

ALTER TABLE iol_lab_token_log ADD COLUMN IF NOT EXISTS detail text;

CREATE TABLE IF NOT EXISTS login_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  ip text,
  ua_hash text,
  ua_brief text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE login_history ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE login_history ADD COLUMN IF NOT EXISTS ip text;

ALTER TABLE login_history ADD COLUMN IF NOT EXISTS ua_hash text;

ALTER TABLE login_history ADD COLUMN IF NOT EXISTS ua_brief text;

ALTER TABLE login_history ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS monthly_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL DEFAULT 0,
  year bigint NOT NULL,
  month bigint NOT NULL,
  broker text NOT NULL,
  deposits double precision DEFAULT 0,
  withdrawals double precision DEFAULT 0,
  pnl_realized double precision DEFAULT 0,
  pnl_unrealized double precision DEFAULT 0,
  capital_inicio double precision DEFAULT 0,
  capital_final double precision DEFAULT 0,
  manual_deposits double precision DEFAULT 0,
  manual_withdrawals double precision DEFAULT 0,
  manual_deposits_native double precision DEFAULT 0,
  manual_withdrawals_native double precision DEFAULT 0,
  UNIQUE (user_id, year, month, broker)
);

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS user_id bigint DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS year bigint;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS month bigint;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS broker text;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS deposits double precision DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS withdrawals double precision DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS pnl_realized double precision DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS pnl_unrealized double precision DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS capital_inicio double precision DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS capital_final double precision DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS manual_deposits double precision DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS manual_withdrawals double precision DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS manual_deposits_native double precision DEFAULT 0;

ALTER TABLE monthly_entries ADD COLUMN IF NOT EXISTS manual_withdrawals_native double precision DEFAULT 0;

CREATE TABLE IF NOT EXISTS news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  external_id text NOT NULL,
  title text NOT NULL,
  summary text,
  url text NOT NULL,
  image_url text,
  published_at text NOT NULL,
  tickers text,
  category text,
  query_source text,
  tags text,
  sentiment text,
  fetched_at text NOT NULL,
  UNIQUE (source, external_id)
);

ALTER TABLE news ADD COLUMN IF NOT EXISTS source text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS external_id text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS title text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS summary text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS url text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS image_url text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS published_at text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS tickers text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS category text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS query_source text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS tags text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS sentiment text;

ALTER TABLE news ADD COLUMN IF NOT EXISTS fetched_at text;

CREATE TABLE IF NOT EXISTS operations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL DEFAULT 0,
  date text NOT NULL,
  broker text NOT NULL,
  asset text NOT NULL,
  op_type text,
  entry_price double precision,
  exit_price double precision,
  quantity double precision,
  pnl_usd double precision DEFAULT 0,
  pnl_pct double precision,
  entry_date text,
  commissions double precision DEFAULT 0,
  notes text,
  undo_meta_json text,
  currency text,
  fx_to_usd double precision,
  cost_basis_consumed double precision
);

ALTER TABLE operations ADD COLUMN IF NOT EXISTS user_id bigint DEFAULT 0;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS broker text;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS asset text;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS op_type text;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS entry_price double precision;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS exit_price double precision;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS quantity double precision;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS pnl_usd double precision DEFAULT 0;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS pnl_pct double precision;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS entry_date text;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS commissions double precision DEFAULT 0;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS undo_meta_json text;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS currency text;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS fx_to_usd double precision;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS cost_basis_consumed double precision;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  token text NOT NULL,
  expires_at text NOT NULL,
  used_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (token)
);

ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS token text;

ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS expires_at text;

ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS used_at text;

ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS plan_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  tier text NOT NULL,
  event_name text NOT NULL,
  feature_id text,
  source text,
  props_json text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

ALTER TABLE plan_events ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE plan_events ADD COLUMN IF NOT EXISTS tier text;

ALTER TABLE plan_events ADD COLUMN IF NOT EXISTS event_name text;

ALTER TABLE plan_events ADD COLUMN IF NOT EXISTS feature_id text;

ALTER TABLE plan_events ADD COLUMN IF NOT EXISTS source text;

ALTER TABLE plan_events ADD COLUMN IF NOT EXISTS props_json text;

ALTER TABLE plan_events ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS plazos_fijos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  banco text NOT NULL,
  capital double precision NOT NULL,
  moneda text NOT NULL DEFAULT 'ARS',
  tasa double precision NOT NULL,
  rate_type text NOT NULL DEFAULT 'TNA',
  fecha_inicio text NOT NULL,
  plazo_dias bigint NOT NULL,
  fecha_vencimiento text NOT NULL,
  renovacion_auto bigint NOT NULL DEFAULT 0,
  modalidad text NOT NULL DEFAULT 'vencimiento',
  pago_frecuencia_meses bigint,
  notes text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  closed_at text
);

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS banco text;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS capital double precision;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS moneda text DEFAULT 'ARS';

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS tasa double precision;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS rate_type text DEFAULT 'TNA';

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS fecha_inicio text;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS plazo_dias bigint;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS fecha_vencimiento text;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS renovacion_auto bigint DEFAULT 0;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS modalidad text DEFAULT 'vencimiento';

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS pago_frecuencia_meses bigint;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE plazos_fijos ADD COLUMN IF NOT EXISTS closed_at text;

CREATE TABLE IF NOT EXISTS positions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL DEFAULT 0,
  broker text NOT NULL,
  asset text NOT NULL,
  is_cash bigint DEFAULT 0,
  buy_price double precision,
  quantity double precision,
  invested double precision,
  tc_compra double precision,
  price_override double precision,
  notes text,
  entry_date text,
  commissions double precision DEFAULT 0,
  currency text,
  asset_type text,
  split_adjusted_through text,
  undo_meta_json text
);

ALTER TABLE positions ADD COLUMN IF NOT EXISTS user_id bigint DEFAULT 0;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS broker text;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS asset text;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS is_cash bigint DEFAULT 0;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS buy_price double precision;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS quantity double precision;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS invested double precision;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS tc_compra double precision;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS price_override double precision;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS entry_date text;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS commissions double precision DEFAULT 0;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS currency text;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS asset_type text;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS split_adjusted_through text;

ALTER TABLE positions ADD COLUMN IF NOT EXISTS undo_meta_json text;

CREATE TABLE IF NOT EXISTS price_backfill_log (
  symbol text,
  desde text NOT NULL,
  ok bigint NOT NULL DEFAULT 1,
  fetched_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (symbol)
);

ALTER TABLE price_backfill_log ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE price_backfill_log ADD COLUMN IF NOT EXISTS desde text;

ALTER TABLE price_backfill_log ADD COLUMN IF NOT EXISTS ok bigint DEFAULT 1;

ALTER TABLE price_backfill_log ADD COLUMN IF NOT EXISTS fetched_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  endpoint text NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_used_at text,
  UNIQUE (user_id, endpoint)
);

ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS endpoint text;

ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS p256dh text;

ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS auth text;

ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS user_agent text;

ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS last_used_at text;

CREATE TABLE IF NOT EXISTS snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  date text NOT NULL,
  total_value double precision NOT NULL,
  total_invested double precision NOT NULL,
  source text,
  net_deposited double precision NOT NULL DEFAULT 0,
  fx_to_usd_blue double precision,
  holdings_json text,
  mtm_coverage double precision,
  base text,
  apto bigint,
  UNIQUE (user_id, date)
);

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS date text;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS total_value double precision;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS total_invested double precision;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS source text;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS net_deposited double precision DEFAULT 0;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS fx_to_usd_blue double precision;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS holdings_json text;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS mtm_coverage double precision;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS base text;

ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS apto bigint;

CREATE TABLE IF NOT EXISTS subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  mp_subscription_id text,
  external_reference text NOT NULL,
  period text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  amount_ars bigint NOT NULL,
  current_period_start text,
  current_period_end text,
  next_charge_date text,
  init_point text,
  last_payment_id text,
  cancelled_at text,
  welcome_email_sent_at text,
  cancellation_email_sent_at text,
  expiration_reminder_sent_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  amount_usd double precision
);

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS mp_subscription_id text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS external_reference text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS period text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS amount_ars bigint;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS current_period_start text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS current_period_end text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS next_charge_date text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS init_point text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS last_payment_id text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS cancelled_at text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS welcome_email_sent_at text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS cancellation_email_sent_at text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS expiration_reminder_sent_at text;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS amount_usd double precision;

CREATE TABLE IF NOT EXISTS trial_consumed (
  email_key text,
  consumed_at text NOT NULL,
  PRIMARY KEY (email_key)
);

ALTER TABLE trial_consumed ADD COLUMN IF NOT EXISTS email_key text;

ALTER TABLE trial_consumed ADD COLUMN IF NOT EXISTS consumed_at text;

CREATE TABLE IF NOT EXISTS trial_email_log (
  user_id bigint NOT NULL,
  kind text NOT NULL,
  sent_at text NOT NULL,
  PRIMARY KEY (user_id, kind)
);

ALTER TABLE trial_email_log ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE trial_email_log ADD COLUMN IF NOT EXISTS kind text;

ALTER TABLE trial_email_log ADD COLUMN IF NOT EXISTS sent_at text;

CREATE TABLE IF NOT EXISTS twr_periods (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  period_start text NOT NULL,
  period_end text NOT NULL,
  month text NOT NULL,
  v0_usd double precision NOT NULL,
  v1_usd double precision NOT NULL,
  flow_usd double precision NOT NULL,
  ret double precision NOT NULL,
  quality text NOT NULL,
  snap_id_start bigint,
  snap_id_end bigint,
  fx_basis text,
  revision bigint NOT NULL DEFAULT 1,
  sealed_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (user_id, month, revision)
);

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS period_start text;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS period_end text;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS month text;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS v0_usd double precision;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS v1_usd double precision;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS flow_usd double precision;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS ret double precision;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS quality text;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS snap_id_start bigint;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS snap_id_end bigint;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS fx_basis text;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS revision bigint DEFAULT 1;

ALTER TABLE twr_periods ADD COLUMN IF NOT EXISTS sealed_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS user_broker_credentials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  broker text NOT NULL,
  api_key_enc text NOT NULL,
  scope text DEFAULT 'read',
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_sync_at text,
  last_sync_status text,
  UNIQUE (user_id, broker)
);

ALTER TABLE user_broker_credentials ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE user_broker_credentials ADD COLUMN IF NOT EXISTS broker text;

ALTER TABLE user_broker_credentials ADD COLUMN IF NOT EXISTS api_key_enc text;

ALTER TABLE user_broker_credentials ADD COLUMN IF NOT EXISTS scope text DEFAULT 'read';

ALTER TABLE user_broker_credentials ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE user_broker_credentials ADD COLUMN IF NOT EXISTS last_sync_at text;

ALTER TABLE user_broker_credentials ADD COLUMN IF NOT EXISTS last_sync_status text;

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  name text,
  password_hash text NOT NULL,
  is_admin bigint NOT NULL DEFAULT 0,
  approved bigint NOT NULL DEFAULT 0,
  tier text,
  password_changed_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_login_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  email_verified bigint DEFAULT 0,
  investor_profile text,
  reengagement_email_sent_at text,
  gift_plan_email_sent_at text,
  trial_invite_email_sent_at text,
  pro_trial_until text,
  pro_trial_used_at text,
  managed_by bigint,
  credit_active_until text,
  credit_anchor_plan text,
  credit_anchor_period text,
  credit_anchor_amount_usd double precision,
  credit_anchor_at text,
  trial_started_at text,
  trial_used_at text,
  trial_ends_at text,
  quota_window_from text,
  UNIQUE (email)
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS email text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS name text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin bigint DEFAULT 0;

ALTER TABLE users ADD COLUMN IF NOT EXISTS approved bigint DEFAULT 0;

ALTER TABLE users ADD COLUMN IF NOT EXISTS tier text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified bigint DEFAULT 0;

ALTER TABLE users ADD COLUMN IF NOT EXISTS investor_profile text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS reengagement_email_sent_at text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS gift_plan_email_sent_at text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_invite_email_sent_at text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS pro_trial_until text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS pro_trial_used_at text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS managed_by bigint;

ALTER TABLE users ADD COLUMN IF NOT EXISTS credit_active_until text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS credit_anchor_plan text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS credit_anchor_period text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS credit_anchor_amount_usd double precision;

ALTER TABLE users ADD COLUMN IF NOT EXISTS credit_anchor_at text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_started_at text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_used_at text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_ends_at text;

ALTER TABLE users ADD COLUMN IF NOT EXISTS quota_window_from text;

CREATE TABLE IF NOT EXISTS watchlist (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  symbol text NOT NULL,
  asset_type text,
  added_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (user_id, symbol)
);

ALTER TABLE watchlist ADD COLUMN IF NOT EXISTS user_id bigint;

ALTER TABLE watchlist ADD COLUMN IF NOT EXISTS symbol text;

ALTER TABLE watchlist ADD COLUMN IF NOT EXISTS asset_type text;

ALTER TABLE watchlist ADD COLUMN IF NOT EXISTS added_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS');

CREATE TABLE IF NOT EXISTS yfinance_cache (
  ticker text NOT NULL,
  kind text NOT NULL,
  fetched_at text NOT NULL,
  payload_json text NOT NULL,
  PRIMARY KEY (ticker, kind)
);

ALTER TABLE yfinance_cache ADD COLUMN IF NOT EXISTS ticker text;

ALTER TABLE yfinance_cache ADD COLUMN IF NOT EXISTS kind text;

ALTER TABLE yfinance_cache ADD COLUMN IF NOT EXISTS fetched_at text;

ALTER TABLE yfinance_cache ADD COLUMN IF NOT EXISTS payload_json text;

CREATE INDEX IF NOT EXISTS idx_adv_alert_ev
                ON advisor_alert_events(advisor_uid, fired_at DESC);

CREATE INDEX IF NOT EXISTS idx_advisor_claim_token ON advisor_claim_tokens(token);

CREATE INDEX IF NOT EXISTS idx_advisor_claim_user ON advisor_claim_tokens(user_id, used_at);

CREATE INDEX IF NOT EXISTS idx_advisor_clients_advisor
                ON advisor_clients(advisor_uid, status);

CREATE INDEX IF NOT EXISTS idx_advisor_clients_client
                ON advisor_clients(client_uid, status);

CREATE INDEX IF NOT EXISTS idx_advisor_groups ON advisor_groups(advisor_uid);

CREATE INDEX IF NOT EXISTS idx_advisor_reports_client
                ON advisor_reports(advisor_uid, client_uid, created_at);

CREATE INDEX IF NOT EXISTS idx_ai_cache_expires
                ON ai_analyses_cache(expires_at);

CREATE INDEX IF NOT EXISTS idx_ai_cache_user_screen
                ON ai_analyses_cache(user_id, screen);

CREATE INDEX IF NOT EXISTS idx_ai_tool_usage_date
                ON ai_tool_usage(date DESC);

CREATE INDEX IF NOT EXISTS idx_ai_tool_usage_tool
                ON ai_tool_usage(tool_name, date DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_user_facts_unique_active
                ON ai_user_facts(user_id, content) WHERE is_active=1;

CREATE INDEX IF NOT EXISTS idx_ai_user_facts_user_active
                ON ai_user_facts(user_id, is_active, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alert_events_user ON alert_events(user_id, fired_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_active ON alerts(active);

CREATE INDEX IF NOT EXISTS idx_alerts_user ON alerts(user_id);

CREATE INDEX IF NOT EXISTS idx_archpos_user ON archived_positions(user_id);

CREATE INDEX IF NOT EXISTS idx_billing_events_mp_data
                ON billing_events(mp_data_id);

CREATE INDEX IF NOT EXISTS idx_billing_events_user
                ON billing_events(user_id);

CREATE INDEX IF NOT EXISTS idx_bond_indices_date ON bond_indices_daily(date);

CREATE INDEX IF NOT EXISTS idx_bond_skips_user ON bond_cashflow_skips(user_id, broker, asset);

CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_ledger_payment_dedup
                ON credit_ledger(source_subscription_id, payment_id, kind)
                WHERE payment_id IS NOT NULL AND source_subscription_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_credit_ledger_user ON credit_ledger(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_deleted_ops_journal_tok
                ON deleted_ops_journal(user_id, token);

CREATE INDEX IF NOT EXISTS idx_email_codes_user_unused
                ON email_verification_codes(user_id, used_at);

CREATE INDEX IF NOT EXISTS idx_events_date ON financial_events(event_date);

CREATE INDEX IF NOT EXISTS idx_events_ticker ON financial_events(ticker);

CREATE INDEX IF NOT EXISTS idx_futpos_abiertas
                ON futures_positions(user_id, closed_at);

CREATE INDEX IF NOT EXISTS idx_futpos_user ON futures_positions(user_id);

CREATE INDEX IF NOT EXISTS idx_goals_user ON goals(user_id);

CREATE INDEX IF NOT EXISTS idx_import_batches_hash
                ON import_batches(user_id, file_hash, status);

CREATE INDEX IF NOT EXISTS idx_import_batches_user
                ON import_batches(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_import_mappings_user ON import_mappings(user_id);

CREATE INDEX IF NOT EXISTS idx_import_norm_batch
                ON import_normalized_tx(batch_id);

CREATE INDEX IF NOT EXISTS idx_import_norm_excluded ON import_normalized_tx(batch_id, excluded_at);

CREATE INDEX IF NOT EXISTS idx_import_norm_fingerprint ON import_normalized_tx(fingerprint);

CREATE INDEX IF NOT EXISTS idx_import_op_links_batch ON import_op_links(batch_id);

CREATE INDEX IF NOT EXISTS idx_import_op_links_op ON import_op_links(operation_id);

CREATE INDEX IF NOT EXISTS idx_import_raw_rows_batch ON import_raw_rows(batch_id);

CREATE INDEX IF NOT EXISTS idx_login_history_ua ON login_history(user_id, ua_hash);

CREATE INDEX IF NOT EXISTS idx_login_history_user ON login_history(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_monthly_user_period ON monthly_entries(user_id, year, month);

CREATE INDEX IF NOT EXISTS idx_news_category ON news(category);

CREATE INDEX IF NOT EXISTS idx_news_published ON news(published_at DESC);

CREATE INDEX IF NOT EXISTS idx_news_qsource_cat ON news(query_source, category);

CREATE INDEX IF NOT EXISTS idx_operations_user_date ON operations(user_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_pf_user ON plazos_fijos(user_id);

CREATE INDEX IF NOT EXISTS idx_plan_events_created
                ON plan_events(created_at);

CREATE INDEX IF NOT EXISTS idx_plan_events_feature
                ON plan_events(feature_id, event_name);

CREATE INDEX IF NOT EXISTS idx_plan_events_user
                ON plan_events(user_id);

CREATE INDEX IF NOT EXISTS idx_positions_user ON positions(user_id);

CREATE INDEX IF NOT EXISTS idx_price_hist_symbol
                ON asset_price_history(symbol, date DESC);

CREATE INDEX IF NOT EXISTS idx_push_user ON push_subscriptions(user_id);

CREATE INDEX IF NOT EXISTS idx_pwd_reset_token ON password_reset_tokens(token);

CREATE INDEX IF NOT EXISTS idx_pwd_reset_user ON password_reset_tokens(user_id, used_at);

CREATE INDEX IF NOT EXISTS idx_snapshots_apto ON snapshots(user_id, apto, date);

CREATE INDEX IF NOT EXISTS idx_snapshots_user_date ON snapshots(user_id, date);

CREATE INDEX IF NOT EXISTS idx_subscriptions_mp_id
                ON subscriptions(mp_subscription_id);

CREATE INDEX IF NOT EXISTS idx_subscriptions_status
                ON subscriptions(status);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user
                ON subscriptions(user_id);

CREATE INDEX IF NOT EXISTS idx_twr_periods_user
                ON twr_periods(user_id, month);

CREATE INDEX IF NOT EXISTS idx_watchlist_user ON watchlist(user_id);

CREATE INDEX IF NOT EXISTS idx_yfinance_cache_fetched
                ON yfinance_cache(fetched_at DESC);

CREATE OR REPLACE VIEW snapshots_medibles AS
                SELECT * FROM snapshots
                 WHERE CASE
                         WHEN apto IS NOT NULL THEN apto
                         WHEN source = 'import'  THEN 0
                         WHEN source = 'browser' THEN 0
                         WHEN source = 'mtm_backfill'
                              THEN (CASE WHEN COALESCE(mtm_coverage, -1) >= 0.90
                                         THEN 1 ELSE 0 END)
                         ELSE 1
                       END = 1;

ALTER TABLE advisor_clients ADD CONSTRAINT fk_advisor_clients_client_uid_users FOREIGN KEY (client_uid) REFERENCES users(id);

ALTER TABLE advisor_clients ADD CONSTRAINT fk_advisor_clients_advisor_uid_users FOREIGN KEY (advisor_uid) REFERENCES users(id);

ALTER TABLE advisor_op_batch_items ADD CONSTRAINT fk_advisor_op_batch_items_batch_id_advisor_op_batches FOREIGN KEY (batch_id) REFERENCES advisor_op_batches(id);

ALTER TABLE advisor_op_batches ADD CONSTRAINT fk_advisor_op_batches_advisor_uid_users FOREIGN KEY (advisor_uid) REFERENCES users(id);

ALTER TABLE brokers ADD CONSTRAINT fk_brokers_parent_broker_id_brokers FOREIGN KEY (parent_broker_id) REFERENCES brokers(id) ON DELETE CASCADE;

ALTER TABLE brokers ADD CONSTRAINT fk_brokers_user_id_users FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE import_normalized_tx ADD CONSTRAINT fk_import_normalized_tx_raw_row_id_import_raw_rows FOREIGN KEY (raw_row_id) REFERENCES import_raw_rows(id) ON DELETE CASCADE;

ALTER TABLE import_normalized_tx ADD CONSTRAINT fk_import_normalized_tx_batch_id_import_batches FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE;

ALTER TABLE import_op_links ADD CONSTRAINT fk_import_op_links_raw_row_id_import_raw_rows FOREIGN KEY (raw_row_id) REFERENCES import_raw_rows(id) ON DELETE CASCADE;

ALTER TABLE import_op_links ADD CONSTRAINT fk_import_op_links_batch_id_import_batches FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE;

ALTER TABLE import_raw_rows ADD CONSTRAINT fk_import_raw_rows_batch_id_import_batches FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE;

ALTER TABLE iol_lab_runs ADD CONSTRAINT fk_iol_lab_runs_user_id_users FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE iol_lab_token_log ADD CONSTRAINT fk_iol_lab_token_log_user_id_users FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE user_broker_credentials ADD CONSTRAINT fk_user_broker_credentials_user_id_users FOREIGN KEY (user_id) REFERENCES users(id);
