CREATE TABLE IF NOT EXISTS advisor_alert_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  client_uid bigint,
  kind text,
  message text,
  pct double precision,
  fired_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  delivered_push bigint NOT NULL DEFAULT 0,
  delivered_email bigint NOT NULL DEFAULT 0,
  seen bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS advisor_alert_state (
  advisor_uid bigint NOT NULL,
  client_uid bigint NOT NULL,
  armed bigint NOT NULL DEFAULT 1,
  last_fired_date text,
  PRIMARY KEY (advisor_uid, client_uid)
);

CREATE TABLE IF NOT EXISTS advisor_alerts (
  advisor_uid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  up_pct double precision,
  down_pct double precision,
  channel text NOT NULL DEFAULT 'both',
  active bigint NOT NULL DEFAULT 1,
  group_id bigint,
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS advisor_brief_log (
  advisor_uid bigint NOT NULL,
  kind text NOT NULL,
  date text NOT NULL,
  sent_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (advisor_uid, kind, date)
);

CREATE TABLE IF NOT EXISTS advisor_claim_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  advisor_uid bigint NOT NULL,
  token text NOT NULL,
  email text NOT NULL,
  expires_at text NOT NULL,
  used_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS advisor_clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  client_uid bigint NOT NULL,
  link_type text NOT NULL DEFAULT 'managed',
  permission text NOT NULL DEFAULT 'read_write',
  status text NOT NULL DEFAULT 'active',
  label text,
  notes text,
  consent_ref text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  revoked_at text,
  phone text,
  UNIQUE (advisor_uid, client_uid)
);

CREATE TABLE IF NOT EXISTS advisor_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  name text NOT NULL,
  rules text NOT NULL DEFAULT '{}',
  excluded text NOT NULL DEFAULT '[]',
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS advisor_op_batch_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id bigint NOT NULL,
  client_uid bigint NOT NULL,
  position_id bigint,
  status text NOT NULL DEFAULT 'ok',
  cost_debited double precision,
  autodep_native double precision,
  autodep_usd double precision,
  autodep_ym text
);

CREATE TABLE IF NOT EXISTS advisor_op_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  asset text NOT NULL,
  op_kind text NOT NULL DEFAULT 'buy',
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  undone_at text
);

CREATE TABLE IF NOT EXISTS advisor_profile (
  advisor_uid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name text,
  cnv_matricula text,
  logo_data text,
  brief_open bigint DEFAULT 1,
  brief_close bigint DEFAULT 1,
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS advisor_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_uid bigint NOT NULL,
  client_uid bigint NOT NULL,
  period_start text NOT NULL,
  period_end text NOT NULL,
  token text NOT NULL,
  payload text NOT NULL,
  wa_text text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS ai_analyses_cache (
  cache_key text,
  user_id bigint NOT NULL,
  screen text NOT NULL,
  result_json text NOT NULL,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  expires_at text NOT NULL,
  packet_hash text NOT NULL,
  model text,
  input_tokens bigint DEFAULT 0,
  output_tokens bigint DEFAULT 0,
  cache_read_tokens bigint DEFAULT 0,
  cache_create_tokens bigint DEFAULT 0,
  cost_usd_cents bigint DEFAULT 0,
  PRIMARY KEY (cache_key)
);

CREATE TABLE IF NOT EXISTS ai_tool_usage (
  user_id bigint NOT NULL,
  date text NOT NULL,
  tool_name text NOT NULL,
  count bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, date, tool_name)
);

CREATE TABLE IF NOT EXISTS ai_usage_daily (
  user_id bigint NOT NULL,
  date text NOT NULL,
  analyses_count bigint NOT NULL DEFAULT 0,
  hub_queries_count bigint NOT NULL DEFAULT 0,
  chat_count bigint NOT NULL DEFAULT 0,
  diag_dismiss_count bigint NOT NULL DEFAULT 0,
  cost_usd_cents bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, date)
);

CREATE TABLE IF NOT EXISTS ai_user_facts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  content text NOT NULL,
  source text NOT NULL DEFAULT 'user_correction',
  is_active bigint NOT NULL DEFAULT 1,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS alert_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id bigint NOT NULL,
  user_id bigint NOT NULL,
  symbol text,
  fired_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  price double precision,
  message text,
  delivered_push bigint NOT NULL DEFAULT 0,
  delivered_email bigint NOT NULL DEFAULT 0,
  seen bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS alert_symbol_state (
  alert_id bigint NOT NULL,
  symbol text NOT NULL,
  armed bigint NOT NULL DEFAULT 1,
  last_fired_date text,
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (alert_id, symbol)
);

CREATE TABLE IF NOT EXISTS alerts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  kind text NOT NULL,
  symbol text,
  scope text NOT NULL DEFAULT 'ticker',
  direction text NOT NULL DEFAULT 'either',
  threshold double precision,
  up_pct double precision,
  down_pct double precision,
  currency text,
  baseline text DEFAULT 'prev_close',
  anchor_price double precision,
  channel text NOT NULL DEFAULT 'both',
  repeat text NOT NULL DEFAULT 'once',
  cooldown_min bigint NOT NULL DEFAULT 360,
  armed bigint NOT NULL DEFAULT 1,
  active bigint NOT NULL DEFAULT 1,
  note text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_evaluated_at text,
  last_fired_at text,
  last_fired_price double precision
);

CREATE TABLE IF NOT EXISTS archived_positions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  section text NOT NULL,
  label text,
  payload text NOT NULL,
  count bigint NOT NULL DEFAULT 0,
  archived_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS asset_last_price (
  symbol text,
  price double precision NOT NULL,
  updated_at text NOT NULL,
  PRIMARY KEY (symbol)
);

CREATE TABLE IF NOT EXISTS asset_price_history (
  symbol text NOT NULL,
  date text NOT NULL,
  price double precision NOT NULL,
  source text,
  fetched_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (symbol, date)
);

CREATE TABLE IF NOT EXISTS billing_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mp_event_id text,
  mp_event_type text,
  mp_data_id text,
  user_id bigint,
  signature_valid bigint DEFAULT 0,
  processed bigint DEFAULT 0,
  raw_payload text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS bond_cashflow_skips (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  broker text NOT NULL,
  asset text NOT NULL,
  date text NOT NULL,
  reason text,
  created_at text NOT NULL,
  UNIQUE (user_id, broker, asset, date)
);

CREATE TABLE IF NOT EXISTS bond_indices_daily (
  index_name text NOT NULL,
  date text NOT NULL,
  value double precision NOT NULL,
  source text,
  updated_at text NOT NULL,
  PRIMARY KEY (index_name, date)
);

CREATE TABLE IF NOT EXISTS broadcast_send_log (
  content_hash text NOT NULL,
  email text NOT NULL,
  sent_at text NOT NULL DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (content_hash, email)
);

CREATE TABLE IF NOT EXISTS brokers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name text NOT NULL,
  currency text NOT NULL DEFAULT 'USDT',
  parent_broker_id bigint,
  UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS config (
  key text NOT NULL,
  value text,
  user_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (key, user_id)
);

CREATE TABLE IF NOT EXISTS credit_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  kind text NOT NULL,
  amount_usd double precision NOT NULL,
  days_delta double precision NOT NULL,
  from_plan text,
  from_period text,
  to_plan text,
  to_period text,
  active_until_before text,
  active_until_after text,
  source_subscription_id text,
  payment_id text,
  note text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS deleted_ops_journal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  token text NOT NULL,
  kind text NOT NULL,
  payload_json text NOT NULL,
  since_date text,
  broker text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  undone_at text
);

CREATE TABLE IF NOT EXISTS email_verification_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  code text NOT NULL,
  expires_at text NOT NULL,
  used_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS financial_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker text NOT NULL,
  event_type text NOT NULL,
  event_date text NOT NULL,
  details text,
  confirmed bigint DEFAULT 0,
  source text,
  fetched_at text NOT NULL,
  UNIQUE (ticker, event_type, event_date)
);

CREATE TABLE IF NOT EXISTS futures_positions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  broker text NOT NULL,
  symbol text NOT NULL,
  base_asset text,
  side text NOT NULL DEFAULT 'long',
  quantity double precision NOT NULL,
  entry_price double precision NOT NULL,
  leverage double precision,
  margin_usd double precision,
  liquidation_price double precision,
  opened_at text NOT NULL,
  notes text,
  closed_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS fx_rates_daily (
  date text,
  blue_venta double precision NOT NULL,
  mep_venta double precision,
  source text DEFAULT 'unknown',
  fetched_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (date)
);

CREATE TABLE IF NOT EXISTS goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  target_usd double precision NOT NULL,
  target_date text NOT NULL,
  expected_return_pct double precision NOT NULL DEFAULT 10,
  label text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS import_batches (
  id text,
  user_id bigint NOT NULL,
  broker text NOT NULL,
  parser_format text NOT NULL,
  file_name text,
  file_hash text NOT NULL,
  total_rows bigint NOT NULL DEFAULT 0,
  valid_rows bigint NOT NULL DEFAULT 0,
  invalid_rows bigint NOT NULL DEFAULT 0,
  status text NOT NULL,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  confirmed_at text,
  reverted_at text,
  route_by_currency bigint NOT NULL DEFAULT 0,
  fund_price_overrides text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS import_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name text NOT NULL,
  mapping_json text NOT NULL,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS import_normalized_tx (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id text NOT NULL,
  raw_row_id bigint NOT NULL,
  date text NOT NULL,
  broker text NOT NULL DEFAULT '',
  operation_type text NOT NULL,
  asset_symbol text,
  asset_name text,
  asset_type text,
  quantity double precision,
  unit_price double precision,
  gross_amount double precision,
  fees double precision DEFAULT 0,
  taxes double precision DEFAULT 0,
  currency text,
  settlement_currency text,
  notes text,
  created_position_id bigint,
  created_operation_id bigint,
  transfer_out bigint NOT NULL DEFAULT 0,
  tc_compra double precision,
  excluded_at text,
  excluded_by bigint,
  fingerprint text,
  gross_amount_usd double precision
);

CREATE TABLE IF NOT EXISTS import_op_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id text NOT NULL,
  raw_row_id bigint,
  position_id bigint,
  operation_id bigint
);

CREATE TABLE IF NOT EXISTS import_raw_rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id text NOT NULL,
  row_index bigint NOT NULL,
  raw_json text NOT NULL,
  status text NOT NULL,
  errors_json text
);

CREATE TABLE IF NOT EXISTS login_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  ip text,
  ua_hash text,
  ua_brief text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS monthly_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL DEFAULT 0,
  year bigint NOT NULL,
  month bigint NOT NULL,
  broker text NOT NULL,
  deposits double precision DEFAULT 0,
  withdrawals double precision DEFAULT 0,
  pnl_realized double precision DEFAULT 0,
  pnl_unrealized double precision DEFAULT 0,
  capital_inicio double precision DEFAULT 0,
  capital_final double precision DEFAULT 0,
  manual_deposits double precision DEFAULT 0,
  manual_withdrawals double precision DEFAULT 0,
  manual_deposits_native double precision DEFAULT 0,
  manual_withdrawals_native double precision DEFAULT 0,
  UNIQUE (user_id, year, month, broker)
);

CREATE TABLE IF NOT EXISTS news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  external_id text NOT NULL,
  title text NOT NULL,
  summary text,
  url text NOT NULL,
  image_url text,
  published_at text NOT NULL,
  tickers text,
  category text,
  query_source text,
  tags text,
  sentiment text,
  fetched_at text NOT NULL,
  UNIQUE (source, external_id)
);

CREATE TABLE IF NOT EXISTS operations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL DEFAULT 0,
  date text NOT NULL,
  broker text NOT NULL,
  asset text NOT NULL,
  op_type text,
  entry_price double precision,
  exit_price double precision,
  quantity double precision,
  pnl_usd double precision DEFAULT 0,
  pnl_pct double precision,
  entry_date text,
  commissions double precision DEFAULT 0,
  notes text,
  undo_meta_json text,
  currency text,
  fx_to_usd double precision,
  cost_basis_consumed double precision
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  token text NOT NULL,
  expires_at text NOT NULL,
  used_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS plan_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  tier text NOT NULL,
  event_name text NOT NULL,
  feature_id text,
  source text,
  props_json text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS plazos_fijos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  banco text NOT NULL,
  capital double precision NOT NULL,
  moneda text NOT NULL DEFAULT 'ARS',
  tasa double precision NOT NULL,
  rate_type text NOT NULL DEFAULT 'TNA',
  fecha_inicio text NOT NULL,
  plazo_dias bigint NOT NULL,
  fecha_vencimiento text NOT NULL,
  renovacion_auto bigint NOT NULL DEFAULT 0,
  modalidad text NOT NULL DEFAULT 'vencimiento',
  pago_frecuencia_meses bigint,
  notes text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  closed_at text
);

CREATE TABLE IF NOT EXISTS positions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL DEFAULT 0,
  broker text NOT NULL,
  asset text NOT NULL,
  is_cash bigint DEFAULT 0,
  buy_price double precision,
  quantity double precision,
  invested double precision,
  tc_compra double precision,
  price_override double precision,
  notes text,
  entry_date text,
  commissions double precision DEFAULT 0,
  currency text,
  asset_type text,
  split_adjusted_through text,
  undo_meta_json text
);

CREATE TABLE IF NOT EXISTS price_backfill_log (
  symbol text,
  desde text NOT NULL,
  ok bigint NOT NULL DEFAULT 1,
  fetched_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (symbol)
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  endpoint text NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_used_at text,
  UNIQUE (user_id, endpoint)
);

CREATE TABLE IF NOT EXISTS snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  date text NOT NULL,
  total_value double precision NOT NULL,
  total_invested double precision NOT NULL,
  source text,
  net_deposited double precision NOT NULL DEFAULT 0,
  fx_to_usd_blue double precision,
  holdings_json text,
  UNIQUE (user_id, date)
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  mp_subscription_id text,
  external_reference text NOT NULL,
  period text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  amount_ars bigint NOT NULL,
  current_period_start text,
  current_period_end text,
  next_charge_date text,
  init_point text,
  last_payment_id text,
  cancelled_at text,
  welcome_email_sent_at text,
  cancellation_email_sent_at text,
  expiration_reminder_sent_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  amount_usd double precision
);

CREATE TABLE IF NOT EXISTS trial_consumed (
  email_key text,
  consumed_at text NOT NULL,
  PRIMARY KEY (email_key)
);

CREATE TABLE IF NOT EXISTS trial_email_log (
  user_id bigint NOT NULL,
  kind text NOT NULL,
  sent_at text NOT NULL,
  PRIMARY KEY (user_id, kind)
);

CREATE TABLE IF NOT EXISTS twr_periods (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  period_start text NOT NULL,
  period_end text NOT NULL,
  month text NOT NULL,
  v0_usd double precision NOT NULL,
  v1_usd double precision NOT NULL,
  flow_usd double precision NOT NULL,
  ret double precision NOT NULL,
  quality text NOT NULL,
  snap_id_start bigint,
  snap_id_end bigint,
  fx_basis text,
  revision bigint NOT NULL DEFAULT 1,
  sealed_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (user_id, month, revision)
);

CREATE TABLE IF NOT EXISTS user_broker_credentials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  broker text NOT NULL,
  api_key_enc text NOT NULL,
  scope text DEFAULT 'read',
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_sync_at text,
  last_sync_status text,
  UNIQUE (user_id, broker)
);

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  name text,
  password_hash text NOT NULL,
  is_admin bigint NOT NULL DEFAULT 0,
  approved bigint NOT NULL DEFAULT 0,
  tier text,
  password_changed_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_login_at text,
  created_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  email_verified bigint DEFAULT 0,
  investor_profile text,
  reengagement_email_sent_at text,
  gift_plan_email_sent_at text,
  managed_by bigint,
  credit_active_until text,
  credit_anchor_plan text,
  credit_anchor_period text,
  credit_anchor_amount_usd double precision,
  credit_anchor_at text,
  trial_started_at text,
  trial_used_at text,
  trial_ends_at text,
  UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS watchlist (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  symbol text NOT NULL,
  asset_type text,
  added_at text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (user_id, symbol)
);

CREATE TABLE IF NOT EXISTS yfinance_cache (
  ticker text NOT NULL,
  kind text NOT NULL,
  fetched_at text NOT NULL,
  payload_json text NOT NULL,
  PRIMARY KEY (ticker, kind)
);

CREATE INDEX IF NOT EXISTS idx_adv_alert_ev
            ON advisor_alert_events(advisor_uid, fired_at DESC);

CREATE INDEX IF NOT EXISTS idx_advisor_claim_token ON advisor_claim_tokens(token);

CREATE INDEX IF NOT EXISTS idx_advisor_claim_user ON advisor_claim_tokens(user_id, used_at);

CREATE INDEX IF NOT EXISTS idx_advisor_clients_advisor
            ON advisor_clients(advisor_uid, status);

CREATE INDEX IF NOT EXISTS idx_advisor_clients_client
            ON advisor_clients(client_uid, status);

CREATE INDEX IF NOT EXISTS idx_advisor_groups ON advisor_groups(advisor_uid);

CREATE INDEX IF NOT EXISTS idx_advisor_reports_client
            ON advisor_reports(advisor_uid, client_uid, created_at);

CREATE INDEX IF NOT EXISTS idx_ai_cache_expires
            ON ai_analyses_cache(expires_at);

CREATE INDEX IF NOT EXISTS idx_ai_cache_user_screen
            ON ai_analyses_cache(user_id, screen);

CREATE INDEX IF NOT EXISTS idx_ai_tool_usage_date
            ON ai_tool_usage(date DESC);

CREATE INDEX IF NOT EXISTS idx_ai_tool_usage_tool
            ON ai_tool_usage(tool_name, date DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_user_facts_unique_active
            ON ai_user_facts(user_id, content) WHERE is_active=1;

CREATE INDEX IF NOT EXISTS idx_ai_user_facts_user_active
            ON ai_user_facts(user_id, is_active, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alert_events_user ON alert_events(user_id, fired_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_active ON alerts(active);

CREATE INDEX IF NOT EXISTS idx_alerts_user ON alerts(user_id);

CREATE INDEX IF NOT EXISTS idx_archpos_user ON archived_positions(user_id);

CREATE INDEX IF NOT EXISTS idx_billing_events_mp_data
            ON billing_events(mp_data_id);

CREATE INDEX IF NOT EXISTS idx_billing_events_user
            ON billing_events(user_id);

CREATE INDEX IF NOT EXISTS idx_bond_indices_date ON bond_indices_daily(date);

CREATE INDEX IF NOT EXISTS idx_bond_skips_user ON bond_cashflow_skips(user_id, broker, asset);

CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_ledger_payment_dedup
            ON credit_ledger(source_subscription_id, payment_id, kind)
            WHERE payment_id IS NOT NULL AND source_subscription_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_credit_ledger_user ON credit_ledger(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_deleted_ops_journal_tok
            ON deleted_ops_journal(user_id, token);

CREATE INDEX IF NOT EXISTS idx_email_codes_user_unused
            ON email_verification_codes(user_id, used_at);

CREATE INDEX IF NOT EXISTS idx_events_date ON financial_events(event_date);

CREATE INDEX IF NOT EXISTS idx_events_ticker ON financial_events(ticker);

CREATE INDEX IF NOT EXISTS idx_futpos_abiertas
            ON futures_positions(user_id, closed_at);

CREATE INDEX IF NOT EXISTS idx_futpos_user ON futures_positions(user_id);

CREATE INDEX IF NOT EXISTS idx_goals_user ON goals(user_id);

CREATE INDEX IF NOT EXISTS idx_import_batches_hash
            ON import_batches(user_id, file_hash, status);

CREATE INDEX IF NOT EXISTS idx_import_batches_user
            ON import_batches(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_import_mappings_user ON import_mappings(user_id);

CREATE INDEX IF NOT EXISTS idx_import_norm_batch
            ON import_normalized_tx(batch_id);

CREATE INDEX IF NOT EXISTS idx_import_norm_excluded ON import_normalized_tx(batch_id, excluded_at);

CREATE INDEX IF NOT EXISTS idx_import_norm_fingerprint ON import_normalized_tx(fingerprint);

CREATE INDEX IF NOT EXISTS idx_import_op_links_batch ON import_op_links(batch_id);

CREATE INDEX IF NOT EXISTS idx_import_op_links_op ON import_op_links(operation_id);

CREATE INDEX IF NOT EXISTS idx_import_raw_rows_batch ON import_raw_rows(batch_id);

CREATE INDEX IF NOT EXISTS idx_login_history_ua ON login_history(user_id, ua_hash);

CREATE INDEX IF NOT EXISTS idx_login_history_user ON login_history(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_monthly_user_period ON monthly_entries(user_id, year, month);

CREATE INDEX IF NOT EXISTS idx_news_category ON news(category);

CREATE INDEX IF NOT EXISTS idx_news_published ON news(published_at DESC);

CREATE INDEX IF NOT EXISTS idx_news_qsource_cat ON news(query_source, category);

CREATE INDEX IF NOT EXISTS idx_operations_user_date ON operations(user_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_pf_user ON plazos_fijos(user_id);

CREATE INDEX IF NOT EXISTS idx_plan_events_created
            ON plan_events(created_at);

CREATE INDEX IF NOT EXISTS idx_plan_events_feature
            ON plan_events(feature_id, event_name);

CREATE INDEX IF NOT EXISTS idx_plan_events_user
            ON plan_events(user_id);

CREATE INDEX IF NOT EXISTS idx_positions_user ON positions(user_id);

CREATE INDEX IF NOT EXISTS idx_price_hist_symbol
            ON asset_price_history(symbol, date DESC);

CREATE INDEX IF NOT EXISTS idx_push_user ON push_subscriptions(user_id);

CREATE INDEX IF NOT EXISTS idx_pwd_reset_token ON password_reset_tokens(token);

CREATE INDEX IF NOT EXISTS idx_pwd_reset_user ON password_reset_tokens(user_id, used_at);

CREATE INDEX IF NOT EXISTS idx_snapshots_user_date ON snapshots(user_id, date);

CREATE INDEX IF NOT EXISTS idx_subscriptions_mp_id
            ON subscriptions(mp_subscription_id);

CREATE INDEX IF NOT EXISTS idx_subscriptions_status
            ON subscriptions(status);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user
            ON subscriptions(user_id);

CREATE INDEX IF NOT EXISTS idx_twr_periods_user
            ON twr_periods(user_id, month);

CREATE INDEX IF NOT EXISTS idx_watchlist_user ON watchlist(user_id);

CREATE INDEX IF NOT EXISTS idx_yfinance_cache_fetched
            ON yfinance_cache(fetched_at DESC);

ALTER TABLE advisor_clients ADD FOREIGN KEY (client_uid) REFERENCES users(id);

ALTER TABLE advisor_clients ADD FOREIGN KEY (advisor_uid) REFERENCES users(id);

ALTER TABLE advisor_op_batch_items ADD FOREIGN KEY (batch_id) REFERENCES advisor_op_batches(id);

ALTER TABLE advisor_op_batches ADD FOREIGN KEY (advisor_uid) REFERENCES users(id);

ALTER TABLE brokers ADD FOREIGN KEY (parent_broker_id) REFERENCES brokers(id) ON DELETE CASCADE;

ALTER TABLE brokers ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE import_normalized_tx ADD FOREIGN KEY (raw_row_id) REFERENCES import_raw_rows(id) ON DELETE CASCADE;

ALTER TABLE import_normalized_tx ADD FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE;

ALTER TABLE import_op_links ADD FOREIGN KEY (raw_row_id) REFERENCES import_raw_rows(id) ON DELETE CASCADE;

ALTER TABLE import_op_links ADD FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE;

ALTER TABLE import_raw_rows ADD FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE;

ALTER TABLE user_broker_credentials ADD FOREIGN KEY (user_id) REFERENCES users(id);
