"""Genera el DDL de Postgres a partir del schema FINAL de SQLite.

Idea clave: main.py tiene 46 bloques `executescript` que son la HISTORIA
incremental del schema (crear tabla, después ALTER, después el índice…). Postgres
arranca de cero: no necesita la historia, sólo el resultado. Así que en vez de
traducir 46 migraciones —donde cada una puede tener su propia trampa— corremos
init_db() sobre un SQLite vacío, leemos el schema que quedó, y lo traducimos una
sola vez.

Lo que hay que traducir:
  INTEGER PRIMARY KEY AUTOINCREMENT → GENERATED ALWAYS AS IDENTITY
  INTEGER (no PK)                   → bigint
  REAL                              → double precision
  TEXT / (sin tipo)                 → text
  BLOB                              → bytea
  DATETIME/TIMESTAMP                → timestamptz  (ojo: acá se guardan como TEXT)
  BOOLEAN 0/1                       → smallint     (NO boolean: el código compara =1)

Decisiones deliberadas:
  · Los 0/1 quedan smallint, no boolean. El código hace `WHERE is_cash=1` en
    decenas de lugares; convertirlos a boolean obliga a tocar todos esos sitios y
    a que un `1` de Python deje de matchear. Es un cambio para después, no para
    la migración.
  · Las fechas quedan TEXT. Están guardadas como 'YYYY-MM-DD' y el código las
    compara y ordena como strings (que para ese formato es correcto). Pasarlas a
    date cambia la semántica de 122 sitios; se hace después, con calma.
La regla general: la migración NO es el momento de mejorar el modelo de datos.
"""
import os
import re
import sys
import tempfile

BACKEND = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BACKEND)
os.chdir(BACKEND)
_t = tempfile.NamedTemporaryFile(suffix=".db", delete=False); _t.close()
os.environ["DB_PATH"] = _t.name
os.environ.setdefault("SECRET_KEY", "x")

import sqlite3
import main  # noqa: E402  (corre init_db() con las 46 migraciones)

conn = sqlite3.connect(main.DB_PATH)

# 🔴 LA RAÍZ DEL 58-vs-60. `init_db()` crea 58 tablas; producción tiene 60. Las
# dos que faltan las crea `pricing/fci.py:ensure_tables()` EN CALIENTE, la
# primera vez que alguien pide el precio de un FCI. Generar el esquema
# preguntándole sólo a `init_db()` es **preguntarle a la fuente equivocada**:
# producción es `init_db()` + `ensure_tables()`. Sin esto, el copiador dejaba
# afuera los precios de los FCI y esas posiciones se valuaban mal.
import pricing.fci as _fci  # noqa: E402
_fci.ensure_tables(conn)
conn.commit()

RESERVADAS = {"user", "order", "group", "check", "default", "window", "references",
              "all", "end", "table", "column", "limit", "offset", "primary", "unique"}


def q(nombre: str) -> str:
    """Entrecomilla si hace falta: Postgres baja todo a minúsculas y tiene más
    palabras reservadas que SQLite."""
    return f'"{nombre}"' if (nombre.lower() in RESERVADAS or nombre != nombre.lower()) else nombre


def tipo_pg(decl: str, es_pk_auto: bool) -> str:
    if es_pk_auto:
        # BY DEFAULT, no ALWAYS. Con ALWAYS, Postgres RECHAZA un INSERT que traiga
        # el id explícito ("cannot insert a non-DEFAULT value into column id") — y
        # eso es justo lo que hace la migración de datos: mete cada fila CON su id
        # original, porque si los ids cambian se rompen todas las referencias
        # (positions→users, import_normalized_tx→import_raw_rows, etc.).
        # Con BY DEFAULT el id explícito entra, y la secuencia se reposiciona
        # después con setval() para que el próximo alta no choque.
        return "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    d = (decl or "").upper().strip()
    if not d:
        return "text"
    if "INT" in d:
        return "bigint"
    if "REAL" in d or "FLOA" in d or "DOUB" in d:
        return "double precision"
    if "NUMERIC" in d or "DECIMAL" in d:
        return "numeric"
    if "BLOB" in d:
        return "bytea"
    if "BOOL" in d:
        return "smallint"      # el código compara =1/=0, no true/false
    return "text"              # TEXT, CHAR, VARCHAR, DATETIME(-como-texto)…


tablas = [r[0] for r in conn.execute(
    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")]

ddl, notas, fks = [], [], []
for t in tablas:
    sql_orig = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (t,)).fetchone()[0] or ""
    cols = conn.execute(f'PRAGMA table_info("{t}")').fetchall()
    pks = [c for c in cols if c[5]]
    # AUTOINCREMENT real: un solo PK INTEGER
    auto = (len(pks) == 1 and (pks[0][2] or "").upper().startswith("INT"))

    piezas = []
    for cid, nombre, decl, notnull, default, pk in cols:
        es_auto = auto and pk == 1
        t_pg = tipo_pg(decl, es_auto)
        p = f"  {q(nombre)} {t_pg}"
        if not es_auto:
            if notnull:
                p += " NOT NULL"
            if default is not None:
                d = str(default)
                # Los DEFAULT de fecha de SQLite devuelven TEXTO, y las columnas
                # quedaron text: hay que emitir el equivalente que también dé
                # texto, con EL MISMO FORMATO. Un `now()` pelado devolvería
                # timestamptz y rompería las comparaciones de string del código.
                du = d.upper().replace(" ", "")
                if du == "CURRENT_TIMESTAMP" or du.startswith("DATETIME('NOW'"):
                    d = "to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')"
                elif du.startswith("DATE('NOW'"):
                    d = "to_char(now() at time zone 'utc', 'YYYY-MM-DD')"
                elif du == "CURRENT_DATE":
                    d = "to_char(now() at time zone 'utc', 'YYYY-MM-DD')"
                p += f" DEFAULT {d}"
        piezas.append(p)

    if pks and not auto:
        piezas.append(f"  PRIMARY KEY ({', '.join(q(c[1]) for c in pks)})")

    # UNIQUE de tabla (los que SQLite guarda como autoindex)
    for idx in conn.execute(f'PRAGMA index_list("{t}")').fetchall():
        if idx[3] == "u" and idx[1].startswith("sqlite_autoindex"):
            icols = [r[2] for r in conn.execute(f'PRAGMA index_info("{idx[1]}")').fetchall()]
            if icols and not (len(icols) == 1 and any(c[1] == icols[0] and c[5] for c in cols)):
                piezas.append(f"  UNIQUE ({', '.join(q(c) for c in icols)})")

    # FKs: van como ALTER al FINAL, no inline. Inline obliga a crear las tablas
    # en orden de dependencia, y con 58 tablas eso es un grafo que no vale la
    # pena resolver: advisor_op_batch_items referenciaba a advisor_op_batches y
    # fallaba sólo por orden alfabético.
    for fk in conn.execute(f'PRAGMA foreign_key_list("{t}")').fetchall():
        _id, _seq, tabla_ref, desde, hacia, on_update, on_delete, _m = fk
        acc = f" ON DELETE {on_delete}" if on_delete and on_delete != "NO ACTION" else ""
        # 🔴 CON NOMBRE, y no es cosmético. `ADD FOREIGN KEY` sin nombre no es
        # idempotente: Postgres le autogenera uno libre (`brokers_user_id_fkey`,
        # después `…_fkey1`) y **crea una segunda constraint idéntica sin dar
        # error**. `_init_db_postgres()` re-aplica este archivo en CADA arranque,
        # así que cada boot sumaba 12 FKs más, cada una validando la tabla hija
        # entera con ACCESS EXCLUSIVE — sobre tablas de ~1M de filas.
        # Su `except DuplicateObject: pass`, con el comentario "la FK ya
        # existía", era letra muerta: ese error nunca llegaba a levantarse.
        # Medido: tres ALTER seguidos → 3 constraints. Con nombre, el segundo
        # levanta DuplicateObject y ahí sí el except hace lo que dice hacer.
        nombre_fk = f"fk_{t}_{desde}_{tabla_ref}"
        fks.append(
            f"ALTER TABLE {q(t)} ADD CONSTRAINT {q(nombre_fk)} "
            f"FOREIGN KEY ({q(desde)}) "
            f"REFERENCES {q(tabla_ref)}({q(hacia or 'id')}){acc};")

    ddl.append(f"CREATE TABLE IF NOT EXISTS {q(t)} (\n" + ",\n".join(piezas) + "\n);")
    if "WITHOUT ROWID" in sql_orig.upper():
        notas.append(f"{t}: era WITHOUT ROWID (en Postgres no aplica, se ignora)")

# Índices explícitos
for nombre, sql in conn.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name"):
    s = sql.strip().rstrip(";")
    s = re.sub(r"\bIF NOT EXISTS\b", "", s, flags=re.I)
    s = re.sub(r"CREATE\s+(UNIQUE\s+)?INDEX", lambda m: f"CREATE {m.group(1) or ''}INDEX IF NOT EXISTS", s, flags=re.I)
    ddl.append(s + ";")

salida = "\n\n".join(ddl + fks)
open(os.path.join(BACKEND, "schema_pg.sql"), "w").write(salida + "\n")
print(f"{len(tablas)} tablas + {len(ddl)-len(tablas)} índices + {len(fks)} FKs → schema_pg.sql")
for n in notas:
    print("  nota:", n)
