"""asset_names — cómo se LLAMA cada activo, para que Rendi lo diga hablando.
═══════════════════════════════════════════════════════════════════════════
La voz de Rendi tiene que decir NOMBRES, no códigos: "Nvidia", no "N-V-D-A";
"Argentina 2030", no "A-L treinta". Nico los escuchó deletreados y suenan mal.
Y no se le puede pedir a la IA que traduzca el código de memoria: los bonos
argentinos los inventa.

GENERADO desde frontend/src/utils/tickers.js — la misma fuente y el mismo
criterio que ai/trade_tickers.py. Si agregás un ticker allá, este archivo queda
corto: `tests/test_ai_asset_names.py` re-parsea el .js y se pone ROJO si los dos
dejan de coincidir, así que el olvido no pasa silencioso.

POR QUÉ ACÁ Y NO MANDÁNDOLO DESDE EL NAVEGADOR (que era el plan original): el
servidor NO usa las posiciones que manda el frontend. `_enrich_chat_snapshot_
valuation` las REEMPLAZA enteras por las que valúa él desde la base, y antes de
eso `_sanitize_chat_snapshot` recorta cada fila a una lista cerrada de campos.
Un `name` puesto del lado del navegador se caía dos veces.

NOMBRES HABLABLES: sin lo que va entre paréntesis ("Argentina 2030 (USD ley
local)" leído dice "paréntesis U-S-D ley local") y sin las siglas societarias
que nadie pronuncia ("Apple Inc." se dice "Apple"). Cuando hay dos listas con
el mismo código gana la primera, igual que `tickerName()` en el frontend.
"""

# ticker → nombre para decir en voz alta
ASSET_NAMES = {
    '1INCH': '1inch',
    'A3': 'A3 Mercados',
    'AAL': 'American Airlines',
    'AAPL': 'Apple',
    'AAVE': 'Aave',
    'ABBV': 'AbbVie',
    'ABEV': 'Ambev',
    'ABNB': 'Airbnb',
    'ABT': 'Abbott Labs',
    'ACN': 'Accenture',
    'ACWI': 'iShares MSCI ACWI',
    'ADA': 'Cardano',
    'ADBE': 'Adobe',
    'ADSK': 'Autodesk',
    'AE38': 'Argentina 2038',
    'AFRM': 'Affirm',
    'AGG': 'iShares Aggregate Bond',
    'AGIX': 'SingularityNET',
    'AGRO': 'Agrometal',
    'AL29': 'Argentina 2029',
    'AL30': 'Argentina 2030',
    'AL35': 'Argentina 2035',
    'AL41': 'Argentina 2041',
    'ALAB': 'Astera Labs',
    'ALGO': 'Algorand',
    'ALUA': 'Aluar',
    'AMAT': 'Applied Materials',
    'AMC': 'AMC Entertainment',
    'AMD': 'AMD',
    'AMGN': 'Amgen',
    'AMZN': 'Amazon',
    'ANET': 'Arista Networks',
    'ANKR': 'Ankr',
    'AO28': 'Bonar 2028',
    'AO29': 'Bonar 2029',
    'APE': 'ApeCoin',
    'APT': 'Aptos',
    'AR': 'Arweave',
    'ARB': 'Arbitrum',
    'ARGT': 'Global X Argentina',
    'ARKG': 'ARK Genomic',
    'ARKK': 'ARK Innovation',
    'ASML': 'ASML Holding',
    'ASTS': 'AST SpaceMobile',
    'ATOM': 'Cosmos',
    'AUSO': 'Autopistas del Sol',
    'AVAX': 'Avalanche',
    'AVGO': 'Broadcom',
    'AXP': 'American Express',
    'AXS': 'Axie Infinity',
    'AZN': 'AstraZeneca',
    'BA': 'Boeing',
    'BA37D': 'Buenos Aires 2037',
    'BABA': 'Alibaba',
    'BAC': 'Bank of America',
    'BAK': 'Braskem',
    'BAL': 'Balancer',
    'BAT': 'Basic Attention Token',
    'BB': 'BlackBerry',
    'BBAR': 'BBVA Argentina',
    'BBD': 'Banco Bradesco',
    'BCH': 'Bitcoin Cash',
    'BHIP': 'Banco Hipotecario',
    'BIDU': 'Baidu',
    'BIOX': 'Bioceres Crop Solutions',
    'BKNG': 'Booking Holdings',
    'BLK': 'BlackRock',
    'BLUR': 'Blur',
    'BMA': 'Banco Macro',
    'BMNR': 'Bitmine Immersion',
    'BMY': 'Bristol-Myers',
    'BNB': 'BNB',
    'BND': 'Vanguard Total Bond Market ETF',
    'BNTX': 'BioNTech',
    'BOLT': 'Boldt',
    'BOME': 'BOOK OF MEME',
    'BONK': 'Bonk',
    'BPAT': 'Banco Patagonia',
    'BPOA7': 'BOPREAL Serie 1-A',
    'BPOB7': 'BOPREAL Serie 1-B',
    'BPOC7': 'BOPREAL Serie 1-C',
    'BPOD7': 'BOPREAL Serie 1-D',
    'BPY26': 'BOPREAL Serie 3 2026',
    'BRENT': 'Petróleo Brent',
    'BRK-B': 'Berkshire Hathaway',
    'BRKB': 'Berkshire Hathaway',
    'BSESN': 'BSE Sensex',
    'BSX': 'Boston Scientific',
    'BTC': 'Bitcoin',
    'BVSP': 'Bovespa',
    'BX': 'Blackstone',
    'BYMA': 'Bolsas y Mercados Argentinos',
    'C': 'Citigroup',
    'CAC': 'CAC 40',
    'CADO': 'Carlos Casado',
    'CAPU': 'Capex',
    'CAPX': 'Capex',
    'CARC': 'Caputo',
    'CAT': 'Caterpillar',
    'CECO2': 'Central Costanera',
    'CEG': 'Constellation Energy',
    'CELO': 'Celo',
    'CELU': 'Celulosa Argentina',
    'CEPU': 'Central Puerto',
    'CFX': 'Conflux',
    'CGCDO': 'CGC 2025',
    'CGPA2': 'Camuzzi Gas Pampeana',
    'CHZ': 'Chiliz',
    'CMCSA': 'Comcast',
    'CMG': 'Chipotle',
    'COIN': 'Coinbase',
    'COME': 'Sociedad Comercial del Plata',
    'COMP': 'Compound',
    'COP': 'ConocoPhillips',
    'COPX': 'Global X Cobre',
    'COST': 'Costco',
    'CRES': 'Cresud',
    'CRM': 'Salesforce',
    'CRV': 'Curve DAO',
    'CRWD': 'CrowdStrike',
    'CRWV': 'CoreWeave',
    'CS49O': 'Cresud 2027',
    'CSC1O': 'Capex 2026',
    'CSCO': 'Cisco',
    'CTIO': 'Consultatio',
    'CVH': 'Cablevisión Holding',
    'CVNA': 'Carvana',
    'CVX': 'Chevron',
    'DASH': 'Dash',
    'DAX': 'DAX',
    'DBC': 'Invesco Commodity',
    'DDOG': 'Datadog',
    'DE': 'John Deere',
    'DEGEN': 'Degen',
    'DGCU2': 'Distribuidora Gas Cuyana',
    'DIA': 'SPDR Dow Jones',
    'DIS': 'Walt Disney',
    'DISN': 'Walt Disney',
    'DJI': 'Dow Jones Industrial',
    'DNC1O': 'Edenor 2030',
    'DOCU': 'DocuSign',
    'DOGE': 'Dogecoin',
    'DOME': 'Domec',
    'DOT': 'Polkadot',
    'DOW': 'Dow',
    'DXY': 'Dollar Index',
    'DYCA': 'Dycasa',
    'DYDX': 'dYdX',
    'EA': 'Electronic Arts',
    'ECOG': 'Ecogas',
    'EDN': 'Edenor',
    'EEM': 'iShares Emerging Markets',
    'EFA': 'iShares MSCI EAFE',
    'EGLD': 'MultiversX',
    'ENA': 'Ethena',
    'ENJ': 'Enjin Coin',
    'ENS': 'Ethereum Name Service',
    'EOG': 'EOG Resources',
    'ES1!': 'E-mini S&P 500 Futuros',
    'ETC': 'Ethereum Classic',
    'ETH': 'Ethereum',
    'ETHA': 'iShares Ethereum',
    'ETHE': 'Grayscale Ethereum',
    'ETSY': 'Etsy',
    'EWJ': 'iShares Japón',
    'EWY': 'iShares Corea del Sur',
    'EWZ': 'iShares Brasil',
    'F': 'Ford',
    'FBTC': 'Fidelity Bitcoin',
    'FERR': 'Ferrum',
    'FET': 'Fetch.ai',
    'FIL': 'Filecoin',
    'FIPL': 'Fiplasto',
    'FLOKI': 'Floki',
    'FLOW': 'Flow',
    'FTM': 'Fantom',
    'FTSE': 'FTSE 100',
    'FXI': 'iShares China Large-Cap',
    'GALA': 'Gala',
    'GBAN': 'Gas Natural BAN',
    'GBTC': 'Grayscale Bitcoin',
    'GCLA': 'Grupo Clarín',
    'GD': 'General Dynamics',
    'GD29': 'Argentina 2029',
    'GD30': 'Argentina 2030',
    'GD35': 'Argentina 2035',
    'GD38': 'Argentina 2038',
    'GD41': 'Argentina 2041',
    'GD46': 'Argentina 2046',
    'GE': 'General Electric',
    'GGAL': 'Grupo Financiero Galicia',
    'GILD': 'Gilead Sciences',
    'GLD': 'SPDR Gold',
    'GLOB': 'Globant',
    'GM': 'General Motors',
    'GME': 'GameStop',
    'GMT': 'STEPN',
    'GMX': 'GMX',
    'GNCAO': 'Genneia 2027',
    'GOLD': 'Oro',
    'GOOG': 'Alphabet',
    'GOOGL': 'Alphabet',
    'GPRK': 'GeoPark',
    'GRIM': 'Grimoldi',
    'GRT': 'The Graph',
    'GS': 'Goldman Sachs',
    'HARG': 'Holcim Argentina',
    'HAVA': 'Havanna',
    'HBAR': 'Hedera',
    'HD': 'Home Depot',
    'HIMS': 'Hims & Hers Health',
    'HMY': 'Harmony Gold',
    'HON': 'Honeywell',
    'HOOD': 'Robinhood',
    'HSI': 'Hang Seng',
    'HUT': 'Hut 8',
    'HYG': 'iShares High Yield',
    'IAU': 'iShares Gold',
    'IBEX': 'IBEX 35',
    'IBIT': 'iShares Bitcoin Trust',
    'IBM': 'IBM',
    'ICP': 'Internet Computer',
    'IEF': 'iShares 7-10Y Treasury',
    'IMX': 'Immutable',
    'INAG': 'Insumos Agroquímicos',
    'INDA': 'iShares India',
    'INJ': 'Injective',
    'INTC': 'Intel',
    'INTU': 'Intuit',
    'INVJ': 'Inversora Juramento',
    'IOTA': 'IOTA',
    'IRC1O': 'IRSA 2028',
    'IRC9O': 'IRSA Propiedades 2030',
    'IRCP': 'IRSA Propiedades',
    'IREN': 'IREN',
    'IRSA': 'IRSA Inversiones',
    'ITUB': 'Itaú Unibanco',
    'IVV': 'iShares S&P 500',
    'IWM': 'iShares Russell 2000',
    'JASMY': 'JasmyCoin',
    'JD': 'JD.com',
    'JMIA': 'Jumia Technologies',
    'JNJ': 'Johnson & Johnson',
    'JPM': 'JPMorgan Chase',
    'JTO': 'Jito',
    'JUP': 'Jupiter',
    'KAS': 'Kaspa',
    'KAVA': 'Kava',
    'KEEL': 'Keel Infrastructure',
    'KLAC': 'KLA',
    'KO': 'Coca-Cola',
    'KOSPI': 'KOSPI',
    'KSM': 'Kusama',
    'LAC': 'Lithium Americas',
    'LAR': 'Lithium Argentina',
    'LCID': 'Lucid Group',
    'LDO': 'Lido DAO',
    'LEDE': 'Ledesma',
    'LI': 'Li Auto',
    'LIN': 'Linde',
    'LINK': 'Chainlink',
    'LLY': 'Eli Lilly',
    'LMT': 'Lockheed Martin',
    'LOMA': 'Loma Negra',
    'LONG': 'Longvie',
    'LQD': 'iShares Investment Grade',
    'LRCX': 'Lam Research',
    'LTC': 'Litecoin',
    'LYFT': 'Lyft',
    'MA': 'Mastercard',
    'MANA': 'Decentraland',
    'MATIC': 'Polygon',
    'MCHI': 'iShares China',
    'MDB': 'MongoDB',
    'MDLZ': 'Mondelez',
    'MELI': 'MercadoLibre',
    'MERVAL': 'S&P MERVAL',
    'META': 'Meta Platforms',
    'METR': 'MetroGas',
    'MEW': 'cat in a dogs world',
    'MGC1O': 'Mastellone Hnos. 2026',
    'MINA': 'Mina',
    'MIRG': 'Mirgor',
    'MKR': 'Maker',
    'MMM': '3M',
    'MOLA': 'Molinos Agro',
    'MORI': 'Morixe',
    'MP': 'MP Materials',
    'MPC': 'Marathon Petroleum',
    'MRK': 'Merck',
    'MRNA': 'Moderna',
    'MRVL': 'Marvell Tech',
    'MS': 'Morgan Stanley',
    'MSFT': 'Microsoft',
    'MSTR': 'Strategy',
    'MU': 'Micron',
    'MUX': 'McEwen',
    'MXX': 'IPC México',
    'N225': 'Nikkei 225',
    'NATGAS': 'Gas Natural',
    'NBIS': 'Nebius Group',
    'NDX': 'Nasdaq 100',
    'NEAR': 'NEAR Protocol',
    'NEO': 'Neo',
    'NET': 'Cloudflare',
    'NFLX': 'Netflix',
    'NIO': 'NIO',
    'NKE': 'Nike',
    'NOC': 'Northrop Grumman',
    'NOKA': 'Nokia',
    'NOW': 'ServiceNow',
    'NQ1!': 'E-mini Nasdaq Futuros',
    'NU': 'Nu Holdings',
    'NVAX': 'Novavax',
    'NVDA': 'NVIDIA',
    'NVO': 'Novo Nordisk',
    'NVS': 'Novartis',
    'NYA': 'NYSE Composite',
    'O': 'Realty Income',
    'OCEAN': 'Ocean Protocol',
    'OEST': 'Oeste Grupo Concesionario',
    'OKLO': 'Oklo',
    'OKTA': 'Okta',
    'ONDS': 'Ondas',
    'ONE': 'Harmony',
    'OP': 'Optimism',
    'ORCL': 'Oracle',
    'ORDI': 'ORDI',
    'OXY': 'Occidental Petroleum',
    'PAGS': 'PagSeguro',
    'PAMP': 'Pampa Energía',
    'PANW': 'Palo Alto Networks',
    'PARA': 'Paramount Global',
    'PATA': 'Importadora Patagonia',
    'PATH': 'UiPath',
    'PBR': 'Petrobras',
    'PCAR': 'Petrolera Pampa',
    'PDD': 'PDD Holdings',
    'PENDLE': 'Pendle',
    'PEP': 'PepsiCo',
    'PEPE': 'Pepe',
    'PFE': 'Pfizer',
    'PG': 'Procter & Gamble',
    'PINS': 'Pinterest',
    'PLTR': 'Palantir',
    'PMCAO': 'Pampa Energía 2027',
    'PMCJO': 'Pampa Energía 2029',
    'POLL': 'Polledo',
    'POPCAT': 'Popcat',
    'PSX': 'Phillips 66',
    'PYPL': 'PayPal',
    'PYTH': 'Pyth Network',
    'QCOM': 'Qualcomm',
    'QNT': 'Quant',
    'QQQ': 'Invesco QQQ',
    'QQQM': 'Invesco Nasdaq 100',
    'RBLX': 'Roblox',
    'RGTI': 'Rigetti Computing',
    'RICH': 'Laboratorios Richmond',
    'RIO': 'Rio Tinto',
    'RIOT': 'Riot Platforms',
    'RIVN': 'Rivian',
    'RKLB': 'Rocket Lab',
    'RNDR': 'Render',
    'ROKU': 'Roku',
    'ROSE': 'Oasis Network',
    'RPL': 'Rocket Pool',
    'RTX': 'RTX',
    'RTY1!': 'E-mini Russell Futuros',
    'RUNE': 'THORChain',
    'RUT': 'Russell 2000',
    'SAMI': 'San Miguel',
    'SAND': 'The Sandbox',
    'SATL': 'Satellogic',
    'SBUX': 'Starbucks',
    'SCHD': 'Schwab US Dividend Equity',
    'SE': 'Sea Limited',
    'SEI': 'Sei',
    'SEMI': 'Molinos Juan Semino',
    'SHIB': 'Shiba Inu',
    'SHOP': 'Shopify',
    'SHY': 'iShares 1-3Y Treasury',
    'SID': 'Companhia Siderúrgica Nacional',
    'SILVER': 'Plata',
    'SLB': 'Schlumberger',
    'SLV': 'iShares Silver',
    'SMH': 'VanEck Semiconductors',
    'SNAP': 'Snap',
    'SNDK': 'SanDisk',
    'SNOW': 'Snowflake',
    'SNX': 'Synthetix',
    'SOFI': 'SoFi Technologies',
    'SOL': 'Solana',
    'SOXL': 'Direxion 3x Semis',
    'SOXX': 'iShares Semiconductors',
    'SPCE': 'Virgin Galactic',
    'SPCX': 'SpaceX',
    'SPGI': 'S&P Global',
    'SPOT': 'Spotify',
    'SPX': 'S&P 500',
    'SPY': 'SPDR S&P 500',
    'SQ': 'Block',
    'SQQQ': 'ProShares -3x Nasdaq',
    'SSEC': 'Shanghai Composite',
    'STNE': 'StoneCo',
    'STOXX50': 'Euro Stoxx 50',
    'STRK': 'Starknet',
    'STX': 'Stacks',
    'SUI': 'Sui',
    'SUPV': 'Grupo Supervielle',
    'SUSHI': 'SushiSwap',
    'T': 'AT&T',
    'T2X5': 'Bonos CER 2025',
    'TEAM': 'Atlassian',
    'TECO2': 'Telecom Argentina',
    'TGLT': 'TGLT',
    'TGN1O': 'TGN 2025',
    'TGNO4': 'Transportadora Gas del Norte',
    'TGSU2': 'Transportadora Gas del Sur',
    'TGT': 'Target',
    'THETA': 'Theta Network',
    'TIA': 'Celestia',
    'TIP': 'iShares TIPS Bond ETF',
    'TLC1O': 'Telecom Argentina 2026',
    'TLC5O': 'Telecom Argentina 2031',
    'TLCMO': 'Telecom Argentina 2031',
    'TLT': 'iShares 20+Y Treasury',
    'TMF': 'Direxion 3x Treasury',
    'TMO': 'Thermo Fisher',
    'TMUS': 'T-Mobile US',
    'TON': 'Toncoin',
    'TQQQ': 'ProShares 3x Nasdaq',
    'TRAN': 'Transener',
    'TRIP': 'Tripadvisor',
    'TRX': 'TRON',
    'TSLA': 'Tesla',
    'TSM': 'TSMC',
    'TTWO': 'Take-Two Interactive',
    'TWLO': 'Twilio',
    'TX26': 'Bonos CER 2026',
    'TX28': 'Bonos CER 2028',
    'TXAR': 'Ternium Argentina',
    'TXN': 'Texas Instruments',
    'TZX26': 'Bonos Cero-Cupón CER 2026',
    'TZX27': 'Bonos Cero-Cupón CER 2027',
    'TZX28': 'Bonos Cero-Cupón CER 2028',
    'U': 'Unity Software',
    'UBER': 'Uber',
    'UNG': 'United States Natural Gas',
    'UNH': 'UnitedHealth',
    'UNI': 'Uniswap',
    'UPRO': 'ProShares 3x S&P 500',
    'UPST': 'Upstart',
    'URA': 'Global X Uranio',
    'USDC': 'USD Coin',
    'USDT': 'Tether',
    'USO': 'United States Oil',
    'V': 'Visa',
    'VALE': 'Vale',
    'VALO': 'Grupo Financiero Valores',
    'VEA': 'Vanguard Developed Markets',
    'VET': 'VeChain',
    'VIG': 'Vanguard Dividend Appreciation',
    'VIST': 'Vista Energy',
    'VIX': 'CBOE Volatility Index',
    'VOO': 'Vanguard S&P 500',
    'VST': 'Vistra Energy',
    'VTI': 'Vanguard Total Stock Market',
    'VWO': 'Vanguard Emerging Markets',
    'VYM': 'Vanguard High Dividend Yield',
    'VZ': 'Verizon',
    'WAVES': 'Waves',
    'WBD': 'Warner Bros. Discovery',
    'WDAY': 'Workday',
    'WFC': 'Wells Fargo',
    'WIF': 'dogwifhat',
    'WLD': 'Worldcoin',
    'WMT': 'Walmart',
    'WTI': 'Petróleo WTI',
    'XLB': 'Materiales',
    'XLC': 'Comunicaciones',
    'XLE': 'Energía',
    'XLF': 'Financiero',
    'XLI': 'Industrial',
    'XLK': 'Tecnología',
    'XLM': 'Stellar',
    'XLP': 'Consumo Defensivo',
    'XLRE': 'Real Estate',
    'XLU': 'Utilities',
    'XLV': 'Salud',
    'XLY': 'Consumo Discrecional',
    'XMR': 'Monero',
    'XOM': 'Exxon Mobil',
    'XPEV': 'XPeng',
    'XRP': 'XRP',
    'XTZ': 'Tezos',
    'XYZ': 'Block',
    'YCA0O': 'YPF Clase XXIII Garantizada 2026',
    'YCAMO': 'YPF Clase XXVII 2026',
    'YCAQO': 'YPF Clase IX 2031',
    'YFI': 'yearn.finance',
    'YM1!': 'E-mini Dow Futuros',
    'YMCFO': 'YPF Clase XXXIX 2028',
    'YPFD': 'YPF',
    'ZEC': 'Zcash',
    'ZIL': 'Zilliqa',
    'ZM': 'Zoom',
    'ZRX': '0x',
    'ZS': 'Zscaler',
}


def asset_name(ticker):
    """El nombre hablable, o None si el activo no está en el catálogo. None es
    una respuesta legítima: el prompt le dice a la IA que en ese caso no
    invente el nombre (un bono que se inventa suena igual de convincente que
    uno real)."""
    if not ticker:
        return None
    return ASSET_NAMES.get(str(ticker).strip().upper())
