"""El caché de PKs no puede devolver `lastrowid=None` en silencio.

EL BUG, medido y reproducido. `pgshim` emula el `lastrowid` de sqlite3 agregándole
`RETURNING "<pk>"` al INSERT, y para eso necesita saber el nombre de la PK. Lo lee
del catálogo UNA vez y lo guarda en `_PKS_CACHE`. El problema eran dos cosas juntas:

  1. **La invalidación era asimétrica.** Un `CREATE TABLE` limpiaba `_COLS_CACHE`
     pero NO `_PKS_CACHE`. Una tabla creada después del primer INSERT del proceso
     quedaba marcada "sin PK" para siempre.
  2. **"No la encontré" y "no tiene PK" eran el mismo `None`.** Hay 18 tablas del
     esquema que legítimamente no tienen PK, así que `None` parecía normal.

El resultado no era un error: era `lastrowid=None`, o sea **claves foráneas en
NULL**. Lo que se ve del otro lado es un `NotNullViolation` en la fila SIGUIENTE
—`brokers.user_id`, por ejemplo— o, peor, una fila colgada de nada si no hay
NOT NULL. Es el modo de falla más caro de este proyecto: el error se convierte en
un número equivocado.

DÓNDE MUERDE EN PRODUCCIÓN. `init_db()` crea las 58 tablas antes de la primera
request, así que el arranque normal está bien (medido: el caché ni se carga durante
`init_db`). Pero hay tablas que se crean EN CALIENTE, fuera de `init_db` —
`pricing/fci.py:177` y `:188`— y ésas caen justo en la ventana.

VERIFICADO QUE FALLAN CON EL COMPORTAMIENTO VIEJO: con la invalidación asimétrica
(`_COLS_CACHE.clear()` en vez de `_invalidar_por_ddl()`),
`test_una_tabla_creada_despues_igual_devuelve_su_id` da `lastrowid=None`.
"""
import os
import unittest

import main

_DSN = os.environ.get("DATABASE_URL", "").strip()


@unittest.skipUnless(getattr(main, "USANDO_PG", False),
                     "el caché de PKs sólo existe en modo Postgres")
class CacheDePKsTest(unittest.TestCase):

    def setUp(self):
        import pgshim
        self.pgshim = pgshim
        self.conn = main.get_db()
        self._limpiar()

    def tearDown(self):
        self._limpiar()
        self.conn.close()
        self.pgshim.limpiar_caches()

    def _limpiar(self):
        for t in ("zz_hija", "zz_madre", "zz_tarde", "zz_sin_pk"):
            try:
                self.conn.execute(f"DROP TABLE IF EXISTS {t}")
            except Exception:
                pass
        self.conn.commit()

    # ── el bug ───────────────────────────────────────────────────────────────
    def test_una_tabla_creada_despues_igual_devuelve_su_id(self):
        """El caso exacto que rompía: primero un INSERT (que carga el caché),
        DESPUÉS un CREATE TABLE, y un INSERT en la tabla nueva."""
        self.conn.execute("CREATE TABLE zz_madre (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, nombre text)")
        self.conn.commit()
        primero = self.conn.execute(
            "INSERT INTO zz_madre (nombre) VALUES (?)", ("carga el cache",)).lastrowid
        self.assertIsNotNone(primero)

        # La tabla nace DESPUÉS de que el caché ya se cargó.
        self.conn.execute("CREATE TABLE zz_tarde (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, nombre text)")
        self.conn.commit()
        tarde = self.conn.execute(
            "INSERT INTO zz_tarde (nombre) VALUES (?)", ("la nueva",)).lastrowid
        self.assertIsNotNone(
            tarde, "lastrowid volvió None para una tabla creada después de que el "
                   "caché de PKs se cargó: eso mete NULL en las claves foráneas")
        self.assertGreater(tarde, 0)

    def test_la_clave_foranea_NO_queda_en_NULL(self):
        """La consecuencia, escrita como la ve el usuario.

        Es el `NotNullViolation` en `brokers.user_id` que aparecía en la suite: no
        lo causaba el broker, lo causaba el `lastrowid` del usuario anterior.
        """
        # Una tabla cualquiera PRIMERO, sólo para que el caché se cargue.
        self.conn.execute("CREATE TABLE zz_tarde (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, nombre text)")
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_tarde (nombre) VALUES (?)", ("carga",))

        # La MADRE nace después: es la que va a devolver el id que se usa de FK.
        # (Si naciera antes, su PK estaría cacheada y el test pasaría aun con el
        # bug puesto — pasó en la primera versión de este archivo.)
        self.conn.execute("CREATE TABLE zz_madre (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, nombre text)")
        self.conn.execute("CREATE TABLE zz_hija (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, madre_id bigint NOT NULL)")
        self.conn.commit()
        mid = self.conn.execute(
            "INSERT INTO zz_madre (nombre) VALUES (?)", ("la madre",)).lastrowid
        self.conn.execute("INSERT INTO zz_hija (madre_id) VALUES (?)", (mid,))
        self.conn.commit()
        r = self.conn.execute("SELECT madre_id FROM zz_hija").fetchone()
        self.assertIsNotNone(r["madre_id"])

    # ── lo que NO tiene que cambiar ──────────────────────────────────────────
    def test_una_tabla_sin_PK_sigue_devolviendo_None(self):
        """Es la DECISIÓN escrita, no un descuido: se devuelve None y se loguea,
        no se levanta excepción.

        ⚠️ En el esquema de hoy esto **no puede pasar**: las 58 tablas tienen PK.
        Se banca igual porque una migración futura podría agregar legítimamente
        una tabla sin PK, y convertir eso en "la app no arranca" sería peor que un
        `lastrowid=None` en una tabla a la que nadie le pide el lastrowid.
        """
        self.conn.execute("CREATE TABLE zz_sin_pk (a text, b bigint)")
        self.conn.commit()
        cur = self.conn.execute("INSERT INTO zz_sin_pk (a, b) VALUES (?,?)", ("x", 1))
        self.assertIsNone(cur.lastrowid)

    def test_el_negativo_se_memoiza_y_no_relee_en_cada_insert(self):
        """Releer el catálogo en cada INSERT de una tabla sin PK sería un viaje a
        la base por fila. Se relee UNA vez y se recuerda."""
        self.conn.execute("CREATE TABLE zz_sin_pk (a text)")
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_sin_pk (a) VALUES (?)", ("x",))
        self.assertIn("zz_sin_pk", self.pgshim._SIN_PK)
        antes = dict(self.pgshim._PKS_CACHE)
        self.conn.execute("INSERT INTO zz_sin_pk (a) VALUES (?)", ("y",))
        self.assertEqual(dict(self.pgshim._PKS_CACHE), antes)

    def test_avisa_fuerte_cuando_una_tabla_no_tiene_PK(self):
        """Si es imposible, tiene que dejar rastro. Un `None` silencioso es
        exactamente lo que hizo que este bug tardara semanas en aparecer."""
        self.conn.execute("CREATE TABLE zz_sin_pk (a text)")
        self.conn.commit()
        with self.assertLogs("pgshim", level="WARNING") as log:
            self.conn.execute("INSERT INTO zz_sin_pk (a) VALUES (?)", ("x",))
        self.assertTrue(any("no tiene clave primaria" in m for m in log.output), log.output)

    # ── PK compuesta: la columna se ELIGE, no se toma la que venga ───────────
    def test_con_PK_compuesta_la_columna_es_estable(self):
        """11 de las 58 tablas tienen PK compuesta, así que el catálogo devuelve
        varias filas para la misma tabla. Sin `ORDER BY` se quedaba con "la que
        llegara primero", que no es determinístico entre corridas."""
        self.conn.execute("CREATE TABLE zz_sin_pk (a text, b text, "
                          "PRIMARY KEY (a, b))")
        self.conn.commit()
        elegidas = set()
        for _ in range(4):
            self.pgshim.limpiar_caches()
            elegidas.add(self.conn._pk_de("zz_sin_pk"))
        self.assertEqual(len(elegidas), 1, f"la columna cambió entre lecturas: {elegidas}")
        self.assertEqual(elegidas.pop(), "a", "con PK compuesta y sin identity, "
                                              "gana la columna de menor attnum")

    def test_con_PK_compuesta_gana_la_columna_de_identidad(self):
        """Si una de las columnas de la PK es la identity, es la que de verdad
        emula el `lastrowid` de SQLite, aunque no sea la primera."""
        self.conn.execute("CREATE TABLE zz_sin_pk (a text, "
                          "b bigint GENERATED BY DEFAULT AS IDENTITY, "
                          "PRIMARY KEY (a, b))")
        self.conn.commit()
        self.pgshim.limpiar_caches()
        self.assertEqual(self.conn._pk_de("zz_sin_pk"), "b")

    # ── el esquema vacío: cortar fuerte en vez de envenenar el caché ─────────
    def test_un_esquema_vacio_LEVANTA_en_vez_de_marcar_todo_sin_PK(self):
        """El estado que dejaba una carrera entre dos procesos.

        Si el catálogo no devuelve NI UNA tabla con PK, estamos mirando el esquema
        equivocado. Cachear eso marcaría TODAS las tablas "sin PK" para siempre y
        cada INSERT del proceso devolvería None en silencio. Se corta acá.
        """
        import psycopg
        from psycopg.conninfo import make_conninfo
        base = main.DATABASE_URL
        with psycopg.connect(base, autocommit=True) as c:
            c.execute('DROP SCHEMA IF EXISTS zz_vacio CASCADE')
            c.execute('CREATE SCHEMA zz_vacio')
        try:
            vacio = self.pgshim.connect(make_conninfo(base, options="-c search_path=zz_vacio"))
            self.pgshim.limpiar_caches()
            vacio.execute("CREATE TABLE sin_pk_nada (a text)")   # sin PK a propósito
            vacio.commit()
            with self.assertRaises(RuntimeError) as cm:
                vacio._pk_de("sin_pk_nada")
            self.assertIn("NINGUNA tabla con clave primaria", str(cm.exception))
            vacio.close()
        finally:
            with psycopg.connect(base, autocommit=True) as c:
                c.execute('DROP SCHEMA IF EXISTS zz_vacio CASCADE')
            self.pgshim.limpiar_caches()


@unittest.skipUnless(getattr(main, "USANDO_PG", False),
                     "el caché de PKs sólo existe en modo Postgres")
class DefensaA_ElDDLInvalidaLosTresCachesTest(unittest.TestCase):
    """DEFENSA A, aislada: un DDL **por el shim** invalida los TRES cachés.

    ⚠️ POR QUÉ ESTE TEST MIRA EL CACHÉ Y NO EL `lastrowid`. Las dos defensas se
    tapaban entre sí: mutando una sola, la suite quedaba verde. Un test que mire
    `lastrowid` no puede aislar A, porque la relectura de B lo rescata igual.
    Así que acá se asserta directo sobre el ESTADO del caché, que es lo único que
    A hace y B no.

    Y no se llama a `limpiar_caches()` en ningún lado a propósito: ése es el
    camino manual que usan los fixtures, y usarlo taparía exactamente lo que se
    quiere medir.
    """

    def setUp(self):
        import pgshim
        self.pgshim = pgshim
        self.conn = main.get_db()
        self.conn.execute("DROP TABLE IF EXISTS zz_a1")
        self.conn.execute("DROP TABLE IF EXISTS zz_a2")
        self.conn.commit()

    def tearDown(self):
        self.conn.execute("DROP TABLE IF EXISTS zz_a1")
        self.conn.execute("DROP TABLE IF EXISTS zz_a2")
        self.conn.commit()
        self.conn.close()
        self.pgshim.limpiar_caches()

    def test_un_CREATE_TABLE_por_el_shim_vacia_el_cache_de_PKs(self):
        self.conn.execute("CREATE TABLE zz_a1 (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY)")
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_a1 DEFAULT VALUES")     # carga el caché
        self.assertTrue(self.pgshim._PKS_CACHE, "el caché tendría que estar cargado")

        self.conn.execute("CREATE TABLE zz_a2 (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY)")
        self.assertEqual(
            dict(self.pgshim._PKS_CACHE), {},
            "el DDL no invalidó _PKS_CACHE: la invalidación quedó asimétrica otra "
            "vez (limpia _COLS_CACHE y no éste), que es el bug original")

    def test_un_CREATE_TABLE_por_el_shim_vacia_tambien_los_negativos(self):
        """`_SIN_PK` es un caché igual que los otros dos: si un DDL lo deja
        intacto, una tabla que ganó su PK en una migración sigue marcada."""
        self.conn.execute("CREATE TABLE zz_a1 (a text)")          # sin PK
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_a1 (a) VALUES (?)", ("x",))
        self.assertIn("zz_a1", self.pgshim._SIN_PK)

        self.conn.execute("CREATE TABLE zz_a2 (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY)")
        self.assertEqual(set(self.pgshim._SIN_PK), set(),
                         "el DDL no limpió _SIN_PK")

    def test_un_executescript_con_DDL_tambien_invalida(self):
        """`init_db` usa `executescript`, que es el otro camino al mismo lugar."""
        self.conn.execute("CREATE TABLE zz_a1 (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY)")
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_a1 DEFAULT VALUES")
        self.assertTrue(self.pgshim._PKS_CACHE)
        self.conn.executescript("CREATE TABLE zz_a2 (id bigint GENERATED BY "
                                "DEFAULT AS IDENTITY PRIMARY KEY);")
        self.assertEqual(dict(self.pgshim._PKS_CACHE), {})


@unittest.skipUnless(getattr(main, "USANDO_PG", False),
                     "el caché de PKs sólo existe en modo Postgres")
class DefensaB_LaRelecturaAnteUnFalloDeCacheTest(unittest.TestCase):
    """DEFENSA B, aislada: la tabla la crea OTRA conexión.

    **Éste es el escenario de PRODUCCIÓN**, y es el que la suite no cubría. En los
    tests de antes el `CREATE TABLE` pasaba por el shim, así que `_invalidar_por_ddl`
    limpiaba el caché y la relectura no hacía falta nunca — mutarla dejaba la suite
    verde.

    En producción la tabla la crea **otro proceso u otra conexión**: es literalmente
    lo que hace `pricing/fci.py:ensure_tables`, y lo que hace cualquier worker. Ahí
    nuestro proceso nunca ve el DDL, la invalidación de A no se entera, y lo único
    que evita el `lastrowid=None` es la relectura.
    """

    def setUp(self):
        import pgshim
        import psycopg
        self.pgshim = pgshim
        self.psycopg = psycopg
        self.conn = main.get_db()
        self._limpiar()

    def tearDown(self):
        self._limpiar()
        self.conn.close()
        self.pgshim.limpiar_caches()

    def _limpiar(self):
        for t in ("zz_b1", "zz_b2"):
            self.conn.execute(f"DROP TABLE IF EXISTS {t}")
        self.conn.commit()

    def _crear_desde_afuera(self, ddl):
        """DDL por una conexión APARTE: nuestro proceso no se entera."""
        with self.psycopg.connect(main.DATABASE_URL, autocommit=True) as otra:
            otra.execute(ddl)

    def test_una_tabla_creada_por_OTRA_conexion_igual_devuelve_su_id(self):
        self.conn.execute("CREATE TABLE zz_b1 (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY)")
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_b1 DEFAULT VALUES")     # carga el caché
        self.assertNotIn("zz_b2", self.pgshim._PKS_CACHE)

        self._crear_desde_afuera(
            "CREATE TABLE zz_b2 (id bigint GENERATED BY DEFAULT AS IDENTITY "
            "PRIMARY KEY, nombre text)")

        cur = self.conn.execute("INSERT INTO zz_b2 (nombre) VALUES (?)", ("x",))
        self.assertIsNotNone(
            cur.lastrowid,
            "lastrowid volvió None para una tabla que creó otra conexión. Es el "
            "caso de pricing/fci.py:ensure_tables y de cualquier worker: nuestro "
            "proceso nunca ve ese DDL, así que la invalidación no alcanza — hace "
            "falta releer el catálogo ante un fallo de caché.")

    def test_y_la_clave_foranea_no_queda_en_NULL(self):
        """La consecuencia, como la ve el usuario."""
        self.conn.execute("CREATE TABLE zz_b1 (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY)")
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_b1 DEFAULT VALUES")
        self._crear_desde_afuera(
            "CREATE TABLE zz_b2 (id bigint GENERATED BY DEFAULT AS IDENTITY "
            "PRIMARY KEY, nombre text)")
        mid = self.conn.execute(
            "INSERT INTO zz_b2 (nombre) VALUES (?)", ("la madre",)).lastrowid
        self.conn.execute("CREATE TABLE zz_b1_hija (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, madre_id bigint NOT NULL)")
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_b1_hija (madre_id) VALUES (?)", (mid,))
        self.conn.commit()
        r = self.conn.execute("SELECT madre_id FROM zz_b1_hija").fetchone()
        self.conn.execute("DROP TABLE IF EXISTS zz_b1_hija")
        self.conn.commit()
        self.assertIsNotNone(r["madre_id"])


@unittest.skipUnless(getattr(main, "USANDO_PG", False),
                     "lee el catálogo de Postgres")
class TodasLasTablasTienenPKTest(unittest.TestCase):
    """La INVARIANTE que sostiene todo lo demás.

    Si ninguna tabla puede quedarse sin clave primaria, entonces un `None` de
    `_pk_de` es SIEMPRE un bug — no "a veces normal". Tratarlo como caso esperado
    es justamente lo que hizo que el bug se escondiera tan bien.

    ⚠️ Este test existe también para que un dato falso no vuelva. El comentario de
    `pgshim` decía "hay 18 tablas sin PK": era FALSO, y el 18 salía de contar
    tablas **sin columna `id`**, que es otra cosa. Verificado por tres caminos
    independientes: 58 tablas, CERO sin PK.

    Si mañana alguien agrega una tabla sin PK, que sea una decisión a propósito y
    no algo que se cuela haciendo que `lastrowid=None` vuelva a parecer normal.
    """

    def test_ninguna_tabla_del_esquema_se_queda_sin_clave_primaria(self):
        conn = main.get_db()
        try:
            filas = conn.execute("""
                SELECT c.relname,
                       EXISTS (SELECT 1 FROM pg_index i
                                WHERE i.indrelid = c.oid AND i.indisprimary)
                  FROM pg_class c
                  JOIN pg_namespace n ON n.oid = c.relnamespace
                 WHERE n.nspname = current_schema() AND c.relkind = 'r'
                 ORDER BY c.relname
            """).fetchall()
        finally:
            conn.close()
        sin_pk = [r[0] for r in filas if not r[1]]
        self.assertGreaterEqual(len(filas), 50, f"esperaba ~58 tablas, vi {len(filas)}")
        self.assertEqual(
            sin_pk, [],
            f"{len(sin_pk)} tabla(s) sin clave primaria: {sin_pk}. Si es a "
            f"propósito, actualizá el comentario de `_SIN_PK` en pgshim.py y este "
            f"test — pero sabiendo que en esas tablas `lastrowid` va a ser None.")


if __name__ == "__main__":
    unittest.main()
