"""El caché de PKs no puede devolver `lastrowid=None` en silencio.

EL BUG, medido y reproducido. `pgshim` emula el `lastrowid` de sqlite3 agregándole
`RETURNING "<pk>"` al INSERT, y para eso necesita saber el nombre de la PK. Lo lee
del catálogo UNA vez y lo guarda en `_PKS_CACHE`. El problema eran dos cosas juntas:

  1. **La invalidación era asimétrica.** Un `CREATE TABLE` limpiaba `_COLS_CACHE`
     pero NO `_PKS_CACHE`. Una tabla creada después del primer INSERT del proceso
     quedaba marcada "sin PK" para siempre.
  2. **"No la encontré" y "no tiene PK" eran el mismo `None`.** Hay 18 tablas del
     esquema que legítimamente no tienen PK, así que `None` parecía normal.

El resultado no era un error: era `lastrowid=None`, o sea **claves foráneas en
NULL**. Lo que se ve del otro lado es un `NotNullViolation` en la fila SIGUIENTE
—`brokers.user_id`, por ejemplo— o, peor, una fila colgada de nada si no hay
NOT NULL. Es el modo de falla más caro de este proyecto: el error se convierte en
un número equivocado.

DÓNDE MUERDE EN PRODUCCIÓN. `init_db()` crea las 58 tablas antes de la primera
request, así que el arranque normal está bien (medido: el caché ni se carga durante
`init_db`). Pero hay tablas que se crean EN CALIENTE, fuera de `init_db` —
`pricing/fci.py:177` y `:188`— y ésas caen justo en la ventana.

VERIFICADO QUE FALLAN CON EL COMPORTAMIENTO VIEJO: con la invalidación asimétrica
(`_COLS_CACHE.clear()` en vez de `_invalidar_por_ddl()`),
`test_una_tabla_creada_despues_igual_devuelve_su_id` da `lastrowid=None`.
"""
import os
import unittest

import main

_DSN = os.environ.get("DATABASE_URL", "").strip()


@unittest.skipUnless(getattr(main, "USANDO_PG", False),
                     "el caché de PKs sólo existe en modo Postgres")
class CacheDePKsTest(unittest.TestCase):

    def setUp(self):
        import pgshim
        self.pgshim = pgshim
        self.conn = main.get_db()
        self._limpiar()

    def tearDown(self):
        self._limpiar()
        self.conn.close()
        self.pgshim.limpiar_caches()

    def _limpiar(self):
        for t in ("zz_hija", "zz_madre", "zz_tarde", "zz_sin_pk"):
            try:
                self.conn.execute(f"DROP TABLE IF EXISTS {t}")
            except Exception:
                pass
        self.conn.commit()

    # ── el bug ───────────────────────────────────────────────────────────────
    def test_una_tabla_creada_despues_igual_devuelve_su_id(self):
        """El caso exacto que rompía: primero un INSERT (que carga el caché),
        DESPUÉS un CREATE TABLE, y un INSERT en la tabla nueva."""
        self.conn.execute("CREATE TABLE zz_madre (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, nombre text)")
        self.conn.commit()
        primero = self.conn.execute(
            "INSERT INTO zz_madre (nombre) VALUES (?)", ("carga el cache",)).lastrowid
        self.assertIsNotNone(primero)

        # La tabla nace DESPUÉS de que el caché ya se cargó.
        self.conn.execute("CREATE TABLE zz_tarde (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, nombre text)")
        self.conn.commit()
        tarde = self.conn.execute(
            "INSERT INTO zz_tarde (nombre) VALUES (?)", ("la nueva",)).lastrowid
        self.assertIsNotNone(
            tarde, "lastrowid volvió None para una tabla creada después de que el "
                   "caché de PKs se cargó: eso mete NULL en las claves foráneas")
        self.assertGreater(tarde, 0)

    def test_la_clave_foranea_NO_queda_en_NULL(self):
        """La consecuencia, escrita como la ve el usuario.

        Es el `NotNullViolation` en `brokers.user_id` que aparecía en la suite: no
        lo causaba el broker, lo causaba el `lastrowid` del usuario anterior.
        """
        # Una tabla cualquiera PRIMERO, sólo para que el caché se cargue.
        self.conn.execute("CREATE TABLE zz_tarde (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, nombre text)")
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_tarde (nombre) VALUES (?)", ("carga",))

        # La MADRE nace después: es la que va a devolver el id que se usa de FK.
        # (Si naciera antes, su PK estaría cacheada y el test pasaría aun con el
        # bug puesto — pasó en la primera versión de este archivo.)
        self.conn.execute("CREATE TABLE zz_madre (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, nombre text)")
        self.conn.execute("CREATE TABLE zz_hija (id bigint GENERATED BY DEFAULT "
                          "AS IDENTITY PRIMARY KEY, madre_id bigint NOT NULL)")
        self.conn.commit()
        mid = self.conn.execute(
            "INSERT INTO zz_madre (nombre) VALUES (?)", ("la madre",)).lastrowid
        self.conn.execute("INSERT INTO zz_hija (madre_id) VALUES (?)", (mid,))
        self.conn.commit()
        r = self.conn.execute("SELECT madre_id FROM zz_hija").fetchone()
        self.assertIsNotNone(r["madre_id"])

    # ── lo que NO tiene que cambiar ──────────────────────────────────────────
    def test_una_tabla_sin_PK_sigue_devolviendo_None(self):
        """Hay 18 tablas así en el esquema (config, fx_rates_daily…). `None` ahí
        es la respuesta CORRECTA y no puede convertirse en un error."""
        self.conn.execute("CREATE TABLE zz_sin_pk (a text, b bigint)")
        self.conn.commit()
        cur = self.conn.execute("INSERT INTO zz_sin_pk (a, b) VALUES (?,?)", ("x", 1))
        self.assertIsNone(cur.lastrowid)

    def test_el_negativo_se_memoiza_y_no_relee_en_cada_insert(self):
        """Releer el catálogo en cada INSERT de una tabla sin PK sería un viaje a
        la base por fila. Se relee UNA vez y se recuerda."""
        self.conn.execute("CREATE TABLE zz_sin_pk (a text)")
        self.conn.commit()
        self.conn.execute("INSERT INTO zz_sin_pk (a) VALUES (?)", ("x",))
        self.assertIn("zz_sin_pk", self.pgshim._SIN_PK)
        antes = dict(self.pgshim._PKS_CACHE)
        self.conn.execute("INSERT INTO zz_sin_pk (a) VALUES (?)", ("y",))
        self.assertEqual(dict(self.pgshim._PKS_CACHE), antes)

    # ── el esquema vacío: cortar fuerte en vez de envenenar el caché ─────────
    def test_un_esquema_vacio_LEVANTA_en_vez_de_marcar_todo_sin_PK(self):
        """El estado que dejaba una carrera entre dos procesos.

        Si el catálogo no devuelve NI UNA tabla con PK, estamos mirando el esquema
        equivocado. Cachear eso marcaría TODAS las tablas "sin PK" para siempre y
        cada INSERT del proceso devolvería None en silencio. Se corta acá.
        """
        import psycopg
        from psycopg.conninfo import make_conninfo
        base = main.DATABASE_URL
        with psycopg.connect(base, autocommit=True) as c:
            c.execute('DROP SCHEMA IF EXISTS zz_vacio CASCADE')
            c.execute('CREATE SCHEMA zz_vacio')
        try:
            vacio = self.pgshim.connect(make_conninfo(base, options="-c search_path=zz_vacio"))
            self.pgshim.limpiar_caches()
            vacio.execute("CREATE TABLE sin_pk_nada (a text)")   # sin PK a propósito
            vacio.commit()
            with self.assertRaises(RuntimeError) as cm:
                vacio._pk_de("sin_pk_nada")
            self.assertIn("NINGUNA tabla con clave primaria", str(cm.exception))
            vacio.close()
        finally:
            with psycopg.connect(base, autocommit=True) as c:
                c.execute('DROP SCHEMA IF EXISTS zz_vacio CASCADE')
            self.pgshim.limpiar_caches()


if __name__ == "__main__":
    unittest.main()
